In [369]:
import pandas as pd
import numpy as np
import os
import matplotlib as plt

In [748]:
markers_df = pd.read_csv("lifu_markers_1_2back_test.csv")
# calibration_complete =markers_df[markers_df["marker"] == "START_EXPERIMENT_RECEIVED"].iloc[-1]
# calibration_complete = calibration_complete["LSL_timestamp"]
markers_df_on = markers_df[markers_df["marker"] =="LIFU_ON"]
markers_df

          Time               marker  LSL_timestamp
0     3.236809  collecting_baseline   1.693274e+06
1     3.258948  collecting_baseline   1.693274e+06
2     3.309343  collecting_baseline   1.693274e+06
3     3.337800  collecting_baseline   1.693274e+06
4     3.393953  collecting_baseline   1.693274e+06
..         ...                  ...            ...
207  48.304111              LIFU_ON   1.693319e+06
208  53.629745             LIFU_OFF   1.693325e+06
209  55.592549              LIFU_ON   1.693326e+06
210  60.915801             LIFU_OFF   1.693332e+06
211  65.102826              LIFU_ON   1.693336e+06

[212 rows x 3 columns]

In [749]:
eeg_df = pd.read_csv("eeg_LSL_gpype2back_test.csv")#("thetaEEG_gpype_2back_-1580742246_20260702_093834.csv")
eeg_df

,Time,Ch01,Ch02,Ch03,Ch04,Ch05,Ch06,Ch07,Ch08,Ch09,Ch10,Ch11,Ch12,Ch13
0,1.693272e+06,199999.968750,199999.96875,199999.96875,199999.96875,73926.976562,199999.968750,199999.96875,1097.605103,1.204737e+06,4.072512e+08,9.742852e+07,1.017940e+08,17.890985
1,1.693272e+06,199999.968750,199999.96875,199999.96875,199999.96875,74181.585938,199999.968750,199999.96875,1958.274780,3.834840e+06,3.950912e+08,9.451942e+07,1.017940e+08,18.089228
2,1.693272e+06,199999.968750,199999.96875,199999.96875,199999.96875,73877.859375,199999.968750,199999.96875,2742.082764,7.519018e+06,3.793589e+08,9.075571e+07,1.017940e+08,18.253036
3,1.693272e+06,199999.968750,199999.96875,199999.96875,199999.96875,73507.687500,199999.968750,199999.96875,3455.947998,1.194358e+07,3.603122e+08,8.619908e+07,8.619908e+07,18.382336
4,1.693272e+06,199999.968750,199999.96875,199999.96875,199999.96875,73673.351562,199999.968750,199999.96875,4107.472656,1.687133e+07,3.384560e+08,8.097033e+07,8.619908e+07,18.479101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16041,1.693337e+06,134414.203125,199999.96875,199999.96875,199999.96875,-6958.413086,134467.593750,199999.96875,-2.221680,4.935863e+00,8.398184e+00,1.454111e+00,1.444730e+00,-259.693542
16042,1.693337e+06,134332.843750,199999.96875,199999.96875,199999.96875,-6697.011719,134526.875000,199999.96875,-2.914265,8.492943e+00,8.330305e+00,1.437872e+00,1.444730e+00,-300.667664
16043,1.693337e+06,134519.375000,199999.96875,199999.96875,199999.96875,-6741.213867,134620.250000,199999.96875,-3.594482,1.292030e+01,8.358971e+00,1.444730e+00,1.444730e+00,-309.641937
16044,1.693337e+06,0.000000,0.00000,0.00000,0.00000,0.000000,0.000000,0.00000,-4.252551,1.808419e+01,8.505150e+00,1.479701e+00,1.444730e+00,-267.596771
16045,1.693337e+06,42430.832031,199999.96875,199999.96875,199999.96875,354.266205,42396.738281,199999.96875,-46.219288,2.136223e+03,2.770955e+03,6.623527e+02,6.710287e+02,37.290028

In [750]:
eeg_df = eeg_df.rename(columns = {"Time": "LSL Time", "Ch08": "Theta Bandpass", "Ch09": "Power", "Ch10": "Moving Average", "Ch11": "Z-score", "Ch12": "Hold", "Ch13": "Trigger Channel"})
eeg_df

,LSL Time,Ch01,Ch02,Ch03,Ch04,Ch05,Ch06,Ch07,Theta Bandpass,Power,Moving Average,Z-score,Hold,Trigger Channel
0,1.693272e+06,199999.968750,199999.96875,199999.96875,199999.96875,73926.976562,199999.968750,199999.96875,1097.605103,1.204737e+06,4.072512e+08,9.742852e+07,1.017940e+08,17.890985
1,1.693272e+06,199999.968750,199999.96875,199999.96875,199999.96875,74181.585938,199999.968750,199999.96875,1958.274780,3.834840e+06,3.950912e+08,9.451942e+07,1.017940e+08,18.089228
2,1.693272e+06,199999.968750,199999.96875,199999.96875,199999.96875,73877.859375,199999.968750,199999.96875,2742.082764,7.519018e+06,3.793589e+08,9.075571e+07,1.017940e+08,18.253036
3,1.693272e+06,199999.968750,199999.96875,199999.96875,199999.96875,73507.687500,199999.968750,199999.96875,3455.947998,1.194358e+07,3.603122e+08,8.619908e+07,8.619908e+07,18.382336
4,1.693272e+06,199999.968750,199999.96875,199999.96875,199999.96875,73673.351562,199999.968750,199999.96875,4107.472656,1.687133e+07,3.384560e+08,8.097033e+07,8.619908e+07,18.479101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16041,1.693337e+06,134414.203125,199999.96875,199999.96875,199999.96875,-6958.413086,134467.593750,199999.96875,-2.221680,4.935863e+00,8.398184e+00,1.454111e+00,1.444730e+00,-259.693542
16042,1.693337e+06,134332.843750,199999.96875,199999.96875,199999.96875,-6697.011719,134526.875000,199999.96875,-2.914265,8.492943e+00,8.330305e+00,1.437872e+00,1.444730e+00,-300.667664
16043,1.693337e+06,134519.375000,199999.96875,199999.96875,199999.96875,-6741.213867,134620.250000,199999.96875,-3.594482,1.292030e+01,8.358971e+00,1.444730e+00,1.444730e+00,-309.641937
16044,1.693337e+06,0.000000,0.00000,0.00000,0.00000,0.000000,0.000000,0.00000,-4.252551,1.808419e+01,8.505150e+00,1.479701e+00,1.444730e+00,-267.596771
16045,1.693337e+06,42430.832031,199999.96875,199999.96875,199999.96875,354.266205,42396.738281,199999.96875,-46.219288,2.136223e+03,2.770955e+03,6.623527e+02,6.710287e+02,37.290028

In [751]:
lifu_on = markers_df[markers_df["marker"]=="LIFU_ON"].copy()
lifu_on_timestamp = lifu_on["LSL_timestamp"]
lifu_on_timestamp = np.array(lifu_on_timestamp)
lifu_on_timestamp

array([1693298.1439491, 1693305.1699361, 1693312.1747948, 1693319.1889808,
       1693326.4774191, 1693335.987696 ])

In [752]:
calibration_complete = 1693298.110062

In [753]:
buffer = []
offline_z = []
medians = []
merged_df = eeg_df
mads = []
last_theta_val = None
last_median_val = None
last_mad_val = None

SONICATION_TIME = 5 #seconds i believe  
COOLDOWN_TIME = 7 #sonication time + cooldown time 
THETA_THRESHOLD_Z = 1.5    # z-score threshold
MU =  2.32
SIGMA =  4.18
MAD_THRESHOLD = 60       # for artifact rejection in baseline collection
INITIAL_CUTOFF = 100.0   # initial power threshold to exclude extreme artifacts
BUFFER_SIZE = 500
sonication_enabled = calibration_complete

# Ch05 = index 4
channel = "Hold"

for i in range(len(merged_df)):
    theta_val = merged_df[channel].iloc[i]   # MUST match online
    if last_theta_val is not None and theta_val == last_theta_val:
        offline_z.append(last_theta_val)
        medians.append(last_median_val)
        mads.append(last_theta_val)
        continue
    # Warm-up
    if len(buffer) <= 200:
        if theta_val < INITIAL_CUTOFF:
            buffer.append(theta_val)
        offline_z.append(np.nan)
        medians.append(np.nan)
        mads.append(np.nan)
        continue

    # Rolling buffer
    if len(buffer) > BUFFER_SIZE:
        buffer.pop(0)

    arr = np.array(buffer)
    median = np.median(arr)
    mad = np.median(np.abs(arr - median)) + 1e-6
    

    # Artifact rejection
    z_art = abs(theta_val - median) / mad
    if z_art > MAD_THRESHOLD:
        offline_z.append(np.nan)
        medians.append(np.nan)
        mads.append(np.nan)
        continue

    # Clean sample
    buffer.append(theta_val)
    last_theta_val = theta_val
    last_median_val = median
    last_mad_val = mad

    # Z-score
    offline_z.append(theta_val)
    medians.append(median)
    mads.append(mad)

merged_df["offline z-score"] = offline_z
merged_df["median"] = medians
merged_df['mad'] = mads

In [754]:
LIFU = np.zeros(len(merged_df))
last_trigger_time = -999

for i in range(len(merged_df)):
    theta_z = merged_df["offline z-score"].iloc[i]
    now = merged_df["LSL Time"].iloc[i]

    if now> sonication_enabled and theta_z > THETA_THRESHOLD_Z and theta_z < MAD_THRESHOLD and (now - last_trigger_time > COOLDOWN_TIME):
        LIFU[i] = 1.0
        last_trigger_time = now

In [755]:
merged_df["LIFU"] = LIFU
merged_df

,LSL Time,Ch01,Ch02,Ch03,Ch04,Ch05,Ch06,Ch07,Theta Bandpass,Power,Moving Average,Z-score,Hold,Trigger Channel,offline z-score,median,mad,LIFU
0,1.693272e+06,199999.968750,199999.96875,199999.96875,199999.96875,73926.976562,199999.968750,199999.96875,1097.605103,1.204737e+06,4.072512e+08,9.742852e+07,1.017940e+08,17.890985,NaN,NaN,NaN,0.0
1,1.693272e+06,199999.968750,199999.96875,199999.96875,199999.96875,74181.585938,199999.968750,199999.96875,1958.274780,3.834840e+06,3.950912e+08,9.451942e+07,1.017940e+08,18.089228,NaN,NaN,NaN,0.0
2,1.693272e+06,199999.968750,199999.96875,199999.96875,199999.96875,73877.859375,199999.968750,199999.96875,2742.082764,7.519018e+06,3.793589e+08,9.075571e+07,1.017940e+08,18.253036,NaN,NaN,NaN,0.0
3,1.693272e+06,199999.968750,199999.96875,199999.96875,199999.96875,73507.687500,199999.968750,199999.96875,3455.947998,1.194358e+07,3.603122e+08,8.619908e+07,8.619908e+07,18.382336,NaN,NaN,NaN,0.0
4,1.693272e+06,199999.968750,199999.96875,199999.96875,199999.96875,73673.351562,199999.968750,199999.96875,4107.472656,1.687133e+07,3.384560e+08,8.097033e+07,8.619908e+07,18.479101,NaN,NaN,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16041,1.693337e+06,134414.203125,199999.96875,199999.96875,199999.96875,-6958.413086,134467.593750,199999.96875,-2.221680,4.935863e+00,8.398184e+00,1.454111e+00,1.444730e+00,-259.693542,1.444730,18.007375,1.444730,0.0
16042,1.693337e+06,134332.843750,199999.96875,199999.96875,199999.96875,-6697.011719,134526.875000,199999.96875,-2.914265,8.492943e+00,8.330305e+00,1.437872e+00,1.444730e+00,-300.667664,1.444730,18.007375,1.444730,0.0
16043,1.693337e+06,134519.375000,199999.96875,199999.96875,199999.96875,-6741.213867,134620.250000,199999.96875,-3.594482,1.292030e+01,8.358971e+00,1.444730e+00,1.444730e+00,-309.641937,1.444730,18.007375,1.444730,0.0
16044,1.693337e+06,0.000000,0.00000,0.00000,0.00000,0.000000,0.000000,0.00000,-4.252551,1.808419e+01,8.505150e+00,1.479701e+00,1.444730e+00,-267.596771,1.444730,18.007375,1.444730,0.0
16045,1.693337e+06,42430.832031,199999.96875,199999.96875,199999.96875,354.266205,42396.738281,199999.96875,-46.219288,2.136223e+03,2.770955e+03,6.623527e+02,6.710287e+02,37.290028,671.028687,18.007375,14.137018,0.0

In [756]:
mask_lifu = merged_df["LIFU"] == 1.0
lifu_on_df = merged_df[mask_lifu]
lifu_on_df["LSL Time"] = lifu_on_df["LSL Time"]
lifu_on_cal = lifu_on_df[lifu_on_df["LSL Time"] > calibration_complete]
lifu_on_cal

C:\Users\jshin\AppData\Local\Temp\ipykernel_23040\4113107194.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lifu_on_df["LSL Time"] = lifu_on_df["LSL Time"]

,LSL Time,Ch01,Ch02,Ch03,Ch04,Ch05,Ch06,Ch07,Theta Bandpass,Power,Moving Average,Z-score,Hold,Trigger Channel,offline z-score,median,mad,LIFU
6594,1.693298e+06,63075.457031,199999.96875,199999.96875,199999.96875,277.256989,63048.605469,199999.96875,5.287420,27.956808,16.200684,3.320737,3.218442,-0.054152,3.218442,4.422082,3.218442,1.0
8343,1.693305e+06,51111.937500,199999.96875,199999.96875,199999.96875,327.420258,51062.156250,199999.96875,3.522665,12.409164,9.033171,1.606022,1.606022,-16.666235,1.606022,2.862997,3.055642,1.0
10092,1.693312e+06,46625.144531,199999.96875,199999.96875,199999.96875,342.845947,46558.957031,199999.96875,-6.683650,44.671165,56.406914,12.939453,13.021322,-16.405624,13.021322,4.364031,4.146283,1.0
11841,1.693319e+06,45618.207031,199999.96875,199999.96875,199999.96875,350.761414,45567.425781,199999.96875,11.215375,125.784645,30.584967,6.761954,7.891293,-15.626019,7.891293,6.818312,7.891293,1.0
13590,1.693326e+06,42597.511719,199999.96875,199999.96875,199999.96875,353.813171,42575.148438,199999.96875,5.493381,30.177227,217.730515,51.533619,48.589977,-15.657715,48.589977,10.369282,48.589977,1.0
15795,1.693336e+06,133375.171875,199999.96875,199999.96875,199999.96875,-8294.106445,133208.968750,199999.96875,-0.013355,0.000178,800.649231,190.987869,50.288414,-0.193651,50.288414,17.620301,13.709424,1.0

In [757]:
offline_ts = np.array(lifu_on_cal['LSL Time'])
offline_ts

array([1693298.1104972, 1693305.1275291, 1693312.1344147, 1693319.1383214,
       1693326.1393499, 1693335.9804633])

In [758]:
lifu_on_timestamp #- offline_ts

array([1693298.1439491, 1693305.1699361, 1693312.1747948, 1693319.1889808,
       1693326.4774191, 1693335.987696 ])

In [759]:
windows = []
for idx, ts in enumerate(offline_ts):
    window = eeg_df[abs(eeg_df['LSL Time'] - ts) < 0.1]
    windows.append(window)
#windows = np.array(windows)
windows[4]

,LSL Time,Ch01,Ch02,Ch03,Ch04,Ch05,Ch06,Ch07,Theta Bandpass,Power,Moving Average,Z-score,Hold,Trigger Channel,offline z-score,median,mad,LIFU
13566,1.693326e+06,43158.054688,199999.96875,199999.96875,199999.96875,354.123138,43120.242188,199999.96875,-11.012564,121.276550,120.054237,28.166086,25.856567,-7.488023,25.856567,10.326056,25.856567,0.0
13567,1.693326e+06,42968.300781,199999.96875,199999.96875,199999.96875,345.301666,42917.207031,199999.96875,-8.344167,69.625122,121.043091,28.402655,25.856567,-7.787417,25.856567,10.326056,25.856567,0.0
13568,1.693326e+06,42250.804688,199999.96875,199999.96875,199999.96875,347.733551,42214.875000,199999.96875,-5.441944,29.614756,121.252357,28.452719,25.856567,-7.988996,25.856567,10.326056,25.856567,0.0
13569,1.693326e+06,42339.855469,199999.96875,199999.96875,199999.96875,355.076813,42320.562500,199999.96875,-2.365880,5.597391,121.023361,28.397934,25.856567,-8.197157,25.856567,10.326056,25.856567,0.0
13570,1.693326e+06,43081.480469,199999.96875,199999.96875,199999.96875,352.883392,43046.769531,199999.96875,0.818838,0.670495,120.756447,28.334076,25.856567,-8.486203,25.856567,10.326056,25.856567,0.0
13571,1.693326e+06,43104.105469,199999.96875,199999.96875,199999.96875,345.325531,43043.925781,199999.96875,4.043288,16.348181,120.876205,28.362728,29.077616,-8.871292,29.077616,10.349335,7.043412,0.0
13572,1.693326e+06,42377.117188,199999.96875,199999.96875,199999.96875,347.208984,42338.898438,199999.96875,7.236412,52.365654,121.793091,28.582077,29.077616,-9.342641,29.077616,10.349335,29.077616,0.0
13573,1.693326e+06,42263.273438,199999.96875,199999.96875,199999.96875,353.908600,42246.867188,199999.96875,10.326701,106.640747,123.864426,29.077616,29.077616,-9.895955,29.077616,10.349335,29.077616,0.0
13574,1.693326e+06,42989.062500,199999.96875,199999.96875,199999.96875,354.361572,42955.398438,199999.96875,13.243955,175.402313,127.358849,29.913601,29.077616,-10.520345,29.077616,10.349335,29.077616,0.0
13575,1.693326e+06,43210.582031,199999.96875,199999.96875,199999.96875,346.565277,43153.023438,199999.96875,15.921026,253.479080,132.427490,31.126196,29.077616,-11.177661,29.077616,10.349335,29.077616,0.0
13576,1.693326e+06,42513.062500,199999.96875,199999.96875,199999.96875,345.134766,42472.292969,199999.96875,18.295511,334.725739,139.085129,32.718925,29.077616,-11.805842,29.077616,10.349335,29.077616,0.0
13577,1.693326e+06,42211.894531,199999.96875,199999.96875,199999.96875,354.647644,42194.250000,199999.96875,20.311291,412.548523,147.203323,34.661083,29.077616,-12.328053,29.077616,10.349335,29.077616,0.0
13578,1.693326e+06,42884.261719,199999.96875,199999.96875,199999.96875,354.361572,42855.457031,199999.96875,21.919918,480.482819,156.516602,36.889141,29.077616,-12.676959,29.077616,10.349335,29.077616,0.0
13579,1.693326e+06,43294.480469,199999.96875,199999.96875,199999.96875,347.232849,43239.210938,199999.96875,23.081757,532.767456,166.641724,39.311420,29.077616,-12.851257,29.077616,10.349335,29.077616,0.0
13580,1.693326e+06,42671.925781,199999.96875,199999.96875,199999.96875,345.110931,42630.437500,199999.96875,23.766932,564.867004,177.108475,41.815422,29.077616,-12.943662,29.077616,10.349335,29.077616,0.0
13581,1.693326e+06,42206.429688,199999.96875,199999.96875,199999.96875,349.307068,42185.363281,199999.96875,23.956024,573.891113,187.399628,44.277424,29.077616,-13.092153,29.077616,10.349335,29.077616,0.0
13582,1.693326e+06,42783.093750,199999.96875,199999.96875,199999.96875,354.099304,42754.937500,199999.96875,23.640539,558.875183,196.996536,46.573334,29.077616,-13.390709,29.077616,10.349335,29.077616,0.0
13583,1.693326e+06,43335.988281,199999.96875,199999.96875,199999.96875,350.570709,43290.523438,199999.96875,22.823130,520.895325,205.426102,48.589977,48.589977,-13.827520,48.589977,10.369282,7.066011,0.0
13584,1.693326e+06,42815.710938,199999.96875,199999.96875,199999.96875,348.114990,42766.957031,199999.96875,21.517620,463.007965,212.305252,50.235706,48.589977,-14.294711,48.589977,10.369282,48.589977,0.0
13585,1.693326e+06,42238.457031,199999.96875,199999.96875,199999.96875,347.709656,42211.207031,199999.96875,19.748734,390.012451,217.377899,51.449261,48.589977,-14.657008,48.589977,10.369282,48.589977,0.0
13586,1.693326e+06,42685.156250,199999.96875,199999.96875,199999.96875,352.859528,42661.699219,199999.96875,17.551565,308.057465,220.541580,52.206116,48.589977,-14.842160,48.589977,10.369282,48.589977,0.0
13587,1.693326e+06,43342.074219,199999.96875,199999.96875,199999.96875,349.831635,43296.031250,199999.96875,14.970770,224.123947,221.860031,52.521538,48.589977,-14.908857,48.589977,10.369282,48.589977,0.0
13588,1.693326e+06,42975.738281,199999.96875,199999.96875,199999.96875,344.467194,42926.082031,199999.96875,12.059529,145.432251,221.561325,52.450073,48.589977,-15.018799,48.589977,10.369282,48.589977,0.0
13589,1.693326e+06,42307.238281,199999.96875,199999.96875,199999.96875,347.781189,42274.210938,199999.96875,8.878291,78.824059,220.020828,52.081535,48.589977,-15.286804,48.589977,10.369282,48.589977,0.0
13590,1.693326e+06,42597.511719,199999.96875,199999.96875,199999.96875,353.813171,42575.148438,199999.96875,5.493381,30.177227,217.730515,51.533619,48.589977,-15.657715,48.589977,10.369282,48.589977,1.0
13591,1.693326e+06,43316.937500,199999.96875,199999.96875,199999.96875,353.908600,43281.148438,199999.96875,1.975513,3.902653,215.257202,50.941914,48.589977,-15.971922,48.589977,10.369282,48.589977,0.0
13592,1.693326e+06,43108.562500,199999.96875,199999.96875,199999.96875,349.450134,43058.156250,199999.96875,-1.601785,2.565717,213.193527,50.448212,48.589977,-16.126730,48.589977,10.369282,48.589977,0.0
13593,1.693326e+06,42395.429688,199999.96875,199999.96875,199999.96875,346.493744,42361.863281,199999.96875,-5.163798,26.664816,212.105194,50.187847,50.187847,-16.153824,50.187847,10.420391,7.092758,0.0
13594,1.693326e+06,42502.835938,199999.96875,199999.96875,199999.96875,352.573425,42480.113281,199999.96875,-8.636259,74.584961,212.479935,50.277496,50.187847,-16.167883,50.187847,10.420391,50.187847,0.0
13595,1.693326e+06,43228.343750,199999.96875,199999.96875,199999.96875,354.290039,43194.394531,199999.96875,-11.947004,142.730911,214.682205,50.804352,50.187847,-16.240444,50.187847,10.420391,50.187847,0.0
13596,1.693326e+06,43243.511719,199999.96875,199999.96875,199999.96875,346.660645,43187.023438,199999.96875,-15.027594,225.828568,218.917969,51.817699,50.187847,-16.338587,50.187847,10.420391,50.187847,0.0
13597,1.693326e+06,42506.742188,199999.96875,199999.96875,199999.96875,345.969238,42472.675781,199999.96875,-17.814877,317.369812,225.213226,53.323742,50.187847,-16.402777,50.187847,10.420391,50.187847,0.0
13598,1.693326e+06,42405.179688,199999.96875,199999.96875,199999.96875,351.429047,42390.636719,199999.96875,-20.252436,410.161133,233.408127,55.284241,50.187847,-16.424225,50.187847,10.420391,50.187847,0.0
13599,1.693326e+06,43112.398438,199999.96875,199999.96875,199999.96875,356.388123,43085.031250,199999.96875,-22.291815,496.924988,243.167770,57.619080,50.187847,-16.421152,50.187847,10.420391,50.187847,0.0
13600,1.693326e+06,43322.355469,199999.96875,199999.96875,199999.96875,345.802338,43272.617188,199999.96875,-23.893555,570.902039,254.009232,60.212730,50.187847,-16.420132,50.187847,10.420391,50.187847,0.0
13601,1.693326e+06,42625.523438,199999.96875,199999.96875,199999.96875,345.134766,42585.281250,199999.96875,-25.027966,626.399109,265.341949,62.923912,50.187847,-16.476166,50.187847,10.420391,50.187847,0.0
13602,1.693326e+06,42334.207031,199999.96875,199999.96875,199999.96875,351.142914,42315.824219,199999.96875,-25.675640,659.238464,276.518494,65.597717,50.187847,-16.626455,50.187847,10.420391,50.187847,0.0
13603,1.693326e+06,42989.875000,199999.96875,199999.96875,199999.96875,356.388123,42958.863281,199999.96875,-25.827765,667.073425,286.891022,68.079201,68.079201,-16.829025,68.079201,10.481324,7.138511,0.0
13604,1.693326e+06,43394.398438,199999.96875,199999.96875,199999.96875,347.495117,43349.648438,199999.96875,-25.486139,649.543274,295.867828,70.226746,68.079201,-17.010107,68.079201,10.481324,68.079201,0.0
13605,1.693326e+06,42763.710938,199999.96875,199999.96875,199999.96875,344.634125,42722.613281,199999.96875,-24.662945,608.260925,302.965485,71.924767,68.079201,-17.136007,68.079201,10.481324,68.079201,0.0
13606,1.693326e+06,42303.281250,199999.96875,199999.96875,199999.96875,351.452820,42276.675781,199999.96875,-23.380230,546.635132,307.851166,73.093590,68.079201,-17.199764,68.079201,10.481324,68.079201,0.0
13607,1.693326e+06,42868.093750,199999.96875,199999.96875,199999.96875,356.388123,42839.335938,199999.96875,-21.669125,469.550964,310.371521,73.696533,68.079201,-17.185202,68.079201,10.481324,68.079201,0.0
13608,1.693326e+06,43424.519531,199999.96875,199999.96875,199999.96875,350.451508,43379.761719,199999.96875,-19.568829,382.939056,310.564850,73.742783,68.079201,-17.080729,68.079201,10.481324,68.079201,0.0
13609,1.693326e+06,42899.136719,199999.96875,199999.96875,199999.96875,343.155914,42855.218750,199999.96875,-17.125437,293.280609,308.656158,73.286171,68.079201,-16.915691,68.079201,10.481324,68.079201,0.0
13610,1.693326e+06,42314.292969,199999.96875,199999.96875,199999.96875,351.977386,42287.968750,199999.96875,-14.390630,207.090210,305.036041,72.420105,68.079201,-16.763147,68.079201,10.481324,68.079201,0.0
13611,1.693326e+06,42758.562500,199999.96875,199999.96875,199999.96875,353.145660,42734.917969,199999.96875,-11.420337,130.424072,300.224121,71.268921,68.079201,-16.696283,68.079201,10.481324,68.079201,0.0
13612,1.693326e+06,43406.085938,199999.96875,199999.96875,199999.96875,352.287292,43364.406250,199999.96875,-8.273390,68.448975,294.822754,69.976730,68.079201,-16.734945,68.079201,10.481324,68.079201,0.0
13613,1.693326e+06,43031.648438,199999.96875,199999.96875,199999.96875,346.398376,42984.156250,199999.96875,-5.010180,25.101904,289.463318,68.694565,68.694565,-16.821360,68.694565,10.523821,7.147381,0.0
13614,1.693326e+06,42356.949219,199999.96875,199999.96875,199999.96875,348.091156,42328.718750,199999.96875,-1.691349,2.860662,284.751648,67.567383,68.694565,-16.845459,68.694565,10.523821,68.694565,0.0
13615,1.693326e+06,42641.906250,199999.96875,199999.96875,199999.96875,354.099304,42621.949219,199999.96875,1.623420,2.635494,281.216492,66.721657,68.694565,-16.721176,68.694565,10.523821,68.694565,0.0
13616,1.693326e+06,43348.648438,199999.96875,199999.96875,199999.96875,353.145660,43310.117188,199999.96875,4.876552,23.780756,279.266602,66.255165,68.694565,-16.458324,68.694565,10.523821,68.694565,0.0

In [760]:
mask_lifu = merged_df["LIFU"] == 1.0
lifu_on_df = merged_df[mask_lifu]
lifu_on_cal = lifu_on_df[lifu_on_df["LSL Time"] > psychopy_started]
lifu_on_cal

,LSL Time,Ch01,Ch02,Ch03,Ch04,Ch05,Ch06,Ch07,Theta Bandpass,Power,Moving Average,Z-score,Hold,Trigger Channel,offline z-score,median,mad,LIFU
6594,1.693298e+06,63075.457031,199999.96875,199999.96875,199999.96875,277.256989,63048.605469,199999.96875,5.287420,27.956808,16.200684,3.320737,3.218442,-0.054152,3.218442,4.422082,3.218442,1.0
8343,1.693305e+06,51111.937500,199999.96875,199999.96875,199999.96875,327.420258,51062.156250,199999.96875,3.522665,12.409164,9.033171,1.606022,1.606022,-16.666235,1.606022,2.862997,3.055642,1.0
10092,1.693312e+06,46625.144531,199999.96875,199999.96875,199999.96875,342.845947,46558.957031,199999.96875,-6.683650,44.671165,56.406914,12.939453,13.021322,-16.405624,13.021322,4.364031,4.146283,1.0
11841,1.693319e+06,45618.207031,199999.96875,199999.96875,199999.96875,350.761414,45567.425781,199999.96875,11.215375,125.784645,30.584967,6.761954,7.891293,-15.626019,7.891293,6.818312,7.891293,1.0
13590,1.693326e+06,42597.511719,199999.96875,199999.96875,199999.96875,353.813171,42575.148438,199999.96875,5.493381,30.177227,217.730515,51.533619,48.589977,-15.657715,48.589977,10.369282,48.589977,1.0
15795,1.693336e+06,133375.171875,199999.96875,199999.96875,199999.96875,-8294.106445,133208.968750,199999.96875,-0.013355,0.000178,800.649231,190.987869,50.288414,-0.193651,50.288414,17.620301,13.709424,1.0

In [761]:
lifu_on_time = lifu_on_cal["LSL Time"]
lifu_on_time = np.array(lifu_on_time)
offline_lifu= lifu_on_time

In [762]:
offline_lifu # because the begin calibration didn't start yet that's why it doesn't

array([1693298.1104972, 1693305.1275291, 1693312.1344147, 1693319.1383214,
       1693326.1393499, 1693335.9804633])

In [763]:
target_ts

array([1002279.2847846, 1002505.9063606])

In [764]:
calibration_complete

1693298.110062

In [766]:
offline_lifu - lifu_on_timestamp

array([-0.0334519, -0.042407 , -0.0403801, -0.0506594, -0.3380692,
       -0.0072327])