In [225]:
import pandas as pd
import numpy as np

In [228]:
markers_df = pd.read_csv("lifu_markers_1_2back_-1580742246.csv")
#calibration_complete =markers_df[markers_df["marker"] == "START_EXPERIMENT_RECEIVED"].iloc[-1]
#calibration_complete = calibration_complete["LSL_timestamp"]
markers_df_on = markers_df[markers_df["marker"] =="LIFU_ON"]
markers_df

           Time               marker  LSL_timestamp
0      3.139750  collecting_baseline  401042.229264
1      3.185993  collecting_baseline  401042.275507
2      3.219655  collecting_baseline  401042.309170
3      3.260183  collecting_baseline  401042.349698
4      3.290719  collecting_baseline  401042.380233
..          ...                  ...            ...
203   88.225168              LIFU_ON  401127.314682
204   93.548595             LIFU_OFF  401132.638109
205   96.273409              LIFU_ON  401135.362923
206  101.583768             LIFU_OFF  401140.673282
207  103.303545              LIFU_ON  401142.393059

[208 rows x 3 columns]

In [198]:
calibration_complete

397939.3731693

In [229]:
eeg_df = pd.read_csv("eeg_LSL_gpype2back_-1580742246.csv")
eeg_df

,Time,Ch01,Ch02,Ch03,Ch04,Ch05,Ch06,Ch07
0,401039.829417,199999.968750,-10266.498047,1.054010e+08,4.349291e+08,1.040500e+08,1.017940e+08,19.106939
1,401039.829566,199999.968750,-8758.502930,7.671138e+07,4.287422e+08,1.025699e+08,1.017940e+08,19.875378
2,401039.829784,199999.968750,-7280.627930,5.300754e+07,4.254989e+08,1.017940e+08,1.017940e+08,20.553970
3,401039.830036,199999.968750,-5851.947754,3.424529e+07,4.243946e+08,1.015298e+08,1.017940e+08,21.003149
4,401039.845197,199999.968750,-4487.628906,2.013881e+07,4.244573e+08,1.015448e+08,1.017940e+08,21.208216
...,...,...,...,...,...,...,...,...
25776,401142.962999,-10796.262695,-12.007365,1.441768e+02,3.837538e+03,9.175161e+02,9.452878e+02,-75.611000
25777,401142.967088,-10788.942383,-18.006073,3.242187e+02,3.768651e+03,9.010361e+02,9.452878e+02,-34.142731
25778,401142.978151,-10791.349609,-23.519312,5.531580e+02,3.682657e+03,8.804636e+02,9.452878e+02,3.758197
25779,401142.978421,-10478.307617,-28.499920,8.122454e+02,3.580433e+03,8.560078e+02,9.452878e+02,-4.691980
25780,401143.980460,0.000000,-32.911133,1.083143e+03,3.463768e+03,8.280975e+02,9.452878e+02,-51.952282

In [230]:
eeg_df = eeg_df.rename(columns = {"Time": "LSL Time", "Ch01": "Raw", "Ch02": "Theta Bandpass", "Ch03": "Power", "Ch04": "Moving Average", "Ch05": "Z-score", "Ch06": "Hold"})
eeg_df

,LSL Time,Raw,Theta Bandpass,Power,Moving Average,Z-score,Hold,Ch07
0,401039.829417,199999.968750,-10266.498047,1.054010e+08,4.349291e+08,1.040500e+08,1.017940e+08,19.106939
1,401039.829566,199999.968750,-8758.502930,7.671138e+07,4.287422e+08,1.025699e+08,1.017940e+08,19.875378
2,401039.829784,199999.968750,-7280.627930,5.300754e+07,4.254989e+08,1.017940e+08,1.017940e+08,20.553970
3,401039.830036,199999.968750,-5851.947754,3.424529e+07,4.243946e+08,1.015298e+08,1.017940e+08,21.003149
4,401039.845197,199999.968750,-4487.628906,2.013881e+07,4.244573e+08,1.015448e+08,1.017940e+08,21.208216
...,...,...,...,...,...,...,...,...
25776,401142.962999,-10796.262695,-12.007365,1.441768e+02,3.837538e+03,9.175161e+02,9.452878e+02,-75.611000
25777,401142.967088,-10788.942383,-18.006073,3.242187e+02,3.768651e+03,9.010361e+02,9.452878e+02,-34.142731
25778,401142.978151,-10791.349609,-23.519312,5.531580e+02,3.682657e+03,8.804636e+02,9.452878e+02,3.758197
25779,401142.978421,-10478.307617,-28.499920,8.122454e+02,3.580433e+03,8.560078e+02,9.452878e+02,-4.691980
25780,401143.980460,0.000000,-32.911133,1.083143e+03,3.463768e+03,8.280975e+02,9.452878e+02,-51.952282

In [231]:
lifu_on = markers_df[markers_df["marker"]=="LIFU_ON"].copy()
lifu_on_timestamp = lifu_on["LSL_timestamp"]
lifu_on_timestamp = np.array(lifu_on_timestamp)
lifu_on_timestamp

array([401119.9158258, 401127.3146819, 401135.3629233, 401142.3930592])

In [232]:
target_ts = lifu_on_timestamp

tol = 1e-2  # tolerance for float comparison

df_matches = eeg_df[
    eeg_df["LSL Time"].apply(
        lambda x: np.any(np.abs(target_ts - x) < tol)
    )
]

df_matches

,LSL Time,Raw,Theta Bandpass,Power,Moving Average,Z-score,Hold,Ch07
20009,401119.906888,-69640.648438,-16.073959,258.372162,38.045208,8.546700,6.527602,-0.195426
20010,401119.907089,-71054.773438,-18.681454,348.996735,43.682117,9.895244,6.527602,-0.245488
20011,401119.907244,-70864.023438,-21.116571,445.909576,51.108307,11.671843,6.527602,-0.246869
20012,401119.913412,-69264.351562,-23.294550,542.636047,60.340382,13.880475,13.880475,-0.270572
20013,401119.914660,-69351.125000,-25.133221,631.678711,71.251686,16.490835,13.880475,-0.331495
20014,401119.915394,-70827.296875,-26.555462,705.192566,83.565674,19.436764,13.880475,-0.382498
20015,401119.919447,-71000.164062,-27.491573,755.786621,96.864708,22.618353,13.880475,-0.365345
21860,401127.311535,-36839.417969,-1.172953,1.375819,9.970009,1.830146,0.830218,2.827827
21861,401127.312961,-37146.738281,0.346487,0.120053,9.967908,1.829643,0.830218,3.001016
21862,401127.313340,-37117.792969,1.972063,3.889032,10.039350,1.846734,1.846734,3.201006
21863,401127.319607,-36782.769531,3.668348,13.456775,10.300281,1.909158,1.846734,3.376846
21864,401127.320721,-36756.492188,5.396253,29.119547,10.872709,2.046103,1.846734,3.486006
21865,401127.320928,-37074.093750,7.113909,50.607708,11.873381,2.285498,1.846734,3.493240
21866,401127.324131,-37141.656250,8.777652,77.047165,13.401652,2.651113,1.846734,3.427193
23872,401135.362172,-22135.734375,-2.220239,4.929461,10.146487,1.872366,1.872366,-1.849298
23873,401135.362400,-22452.380859,-0.756977,0.573014,10.157898,1.875095,1.872366,-1.830452
23874,401135.366255,-22514.058594,0.831282,0.691031,10.171713,1.878400,1.872366,-1.727740
23875,401135.366850,-22185.447266,2.509531,6.297743,10.297539,1.908502,1.872366,-1.539183
23876,401135.367042,-22067.214844,4.238969,17.968863,10.656487,1.994375,1.872366,-1.293430
23877,401135.367201,-22387.150391,5.977828,35.734425,11.370303,2.165144,1.872366,-1.061653
23878,401135.370032,-22531.890625,7.682256,59.017059,12.549248,2.447189,1.872366,-0.907385
25629,401142.387560,-12520.791992,-11.692810,136.721802,15.974585,3.266647,0.222731,-16.403803
25630,401142.387788,-12417.984375,-12.053815,145.294434,18.878214,3.961295,0.222731,-16.403961
25631,401142.388831,-12766.411133,-12.196404,148.752274,21.851908,4.672705,0.222731,-16.400070
25632,401142.392475,-12930.560547,-12.095312,146.296585,24.777197,5.372535,5.372535,-16.347982

In [233]:
lifu_on_timestamp[-1]

401142.3930592

In [234]:
merged_df = eeg_df

In [245]:
buffer = []
offline_z = []
last_theta_val = None

MU = 2.32
SIGMA = 4.18
MAD_THRESHOLD = 60
THETA_THRESHOLD_Z = 1.5
INITIAL_CUTOFF = 100.0
BUFFER_SIZE = 500
COOLDOWN_TIME = 7
sonication_enabled = calibration_complete

# Ch05 = index 4
channel = "Hold"

for i in range(len(merged_df)):
    theta_val = merged_df[channel].iloc[i]   # MUST match online
    if last_theta_val is not None and theta_val == last_theta_val:
        offline_z.append(last_theta_val) 
        continue
    # Warm-up
    if len(buffer) <= 200:
        if theta_val < INITIAL_CUTOFF:
            buffer.append(theta_val)
        offline_z.append(np.nan)
        continue

    # Rolling buffer
    if len(buffer) > BUFFER_SIZE:
        buffer.pop(0)

    arr = np.array(buffer)
    median = np.median(arr)
    mad = np.median(np.abs(arr - median)) + 1e-6

    # Artifact rejection
    z_art = abs(theta_val - median) / mad
    if z_art > MAD_THRESHOLD:
        offline_z.append(np.nan)
        continue

    # Clean sample
    buffer.append(theta_val)
    last_theta_val = theta_val

    # Z-score
    offline_z.append(theta_val)

merged_df["offline z-score"] = offline_z

In [246]:
LIFU = np.zeros(len(merged_df))
last_trigger_time = -999

for i in range(len(merged_df)):
    theta_z = merged_df["offline z-score"].iloc[i]
    now = merged_df["LSL Time"].iloc[i]

    if now> sonication_enabled and theta_z > THETA_THRESHOLD_Z and theta_z < MAD_THRESHOLD and (now - last_trigger_time > COOLDOWN_TIME):
        LIFU[i] = 1.0
        last_trigger_time = now

In [247]:
merged_df["LIFU"] = LIFU
merged_df

,LSL Time,Raw,Theta Bandpass,Power,Moving Average,Z-score,Hold,Ch07,offline z-score,LIFU
0,401039.829417,199999.968750,-10266.498047,1.054010e+08,4.349291e+08,1.040500e+08,1.017940e+08,19.106939,NaN,0.0
1,401039.829566,199999.968750,-8758.502930,7.671138e+07,4.287422e+08,1.025699e+08,1.017940e+08,19.875378,NaN,0.0
2,401039.829784,199999.968750,-7280.627930,5.300754e+07,4.254989e+08,1.017940e+08,1.017940e+08,20.553970,NaN,0.0
3,401039.830036,199999.968750,-5851.947754,3.424529e+07,4.243946e+08,1.015298e+08,1.017940e+08,21.003149,NaN,0.0
4,401039.845197,199999.968750,-4487.628906,2.013881e+07,4.244573e+08,1.015448e+08,1.017940e+08,21.208216,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...
25776,401142.962999,-10796.262695,-12.007365,1.441768e+02,3.837538e+03,9.175161e+02,9.452878e+02,-75.611000,NaN,0.0
25777,401142.967088,-10788.942383,-18.006073,3.242187e+02,3.768651e+03,9.010361e+02,9.452878e+02,-34.142731,NaN,0.0
25778,401142.978151,-10791.349609,-23.519312,5.531580e+02,3.682657e+03,8.804636e+02,9.452878e+02,3.758197,NaN,0.0
25779,401142.978421,-10478.307617,-28.499920,8.122454e+02,3.580433e+03,8.560078e+02,9.452878e+02,-4.691980,NaN,0.0
25780,401143.980460,0.000000,-32.911133,1.083143e+03,3.463768e+03,8.280975e+02,9.452878e+02,-51.952282,NaN,0.0

In [248]:
mask_lifu = merged_df["LIFU"] == 1.0
lifu_on = merged_df[mask_lifu]
lifu_on["LSL Time"] = lifu_on["LSL Time"]
lifu_on_cal = lifu_on[lifu_on["LSL Time"] > calibration_complete]
lifu_on_cal

C:\Users\jshin\AppData\Local\Temp\ipykernel_5892\10077578.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lifu_on["LSL Time"] = lifu_on["LSL Time"]

,LSL Time,Raw,Theta Bandpass,Power,Moving Average,Z-score,Hold,Ch07,offline z-score,LIFU
15882,401103.389847,2808.594971,-62.685814,3929.511230,103.159447,24.124268,24.124268,11.157522,24.124268,1.0
18172,401112.550907,-82724.687500,25.444590,647.427124,253.068817,59.987755,59.987755,-0.082841,59.987755,1.0
19923,401119.555996,-71103.234375,-3.971475,15.772612,99.387619,23.221918,23.204041,0.597337,23.204041,1.0
21862,401127.313340,-37117.792969,1.972063,3.889032,10.039350,1.846734,1.846734,3.201006,1.846734,1.0
23872,401135.362172,-22135.734375,-2.220239,4.929461,10.146487,1.872366,1.872366,-1.849298,1.872366,1.0
25632,401142.392475,-12930.560547,-12.095312,146.296585,24.777197,5.372535,5.372535,-16.347982,5.372535,1.0

In [239]:
here = lifu_on_cal.iloc[0]
here['LSL Time']

401103.3898471

In [240]:
lifu_on_time = lifu_on_cal["LSL Time"]
lifu_on_time = np.array(lifu_on_time)
offline_lifu= lifu_on_time

In [249]:
offline_lifu[2:] - target_ts

array([-0.3598298, -0.0013423, -0.0007517, -0.0005843])

In [251]:
offline_lifu

array([401103.3898471, 401112.5509066, 401119.555996 , 401127.3133396,
       401135.3621716, 401142.3924749])

In [244]:
target_ts

array([401119.9158258, 401127.3146819, 401135.3629233, 401142.3930592])

In [131]:
start_time = eeg_df['LSL Time'].iloc[0] 
target_ts_onset = target_ts - start_time
target_ts_onset

array([ 54.3462151,  65.4100042,  75.4221328,  88.1576968,  98.8652931,
       109.1215809])

In [69]:
calibration_complete

1783460.5785901

In [38]:
start_time

313184.1540356

In [185]:
mask_merged = merged_df['offline z-score'].isna()
merged_mask_df = merged_df[mask_merged]
merged_df.iloc[7100:7150]

,LSL Time,Raw,Theta Bandpass,Power,Moving Average,Z-score,Hold,Ch07,offline z-score,LIFU
7100,393877.651769,185667.546875,-0.943831,0.890817,366.189880,87.050209,83.577621,0.568381,83.577621,0.0
7101,393877.655689,184887.046875,-1.085795,1.178951,360.809723,85.763100,83.577621,0.589320,83.577621,0.0
7102,393877.663072,186060.875000,-1.283985,1.648617,351.674469,83.577621,83.577621,0.541268,83.577621,0.0
7103,393877.672471,187225.953125,-1.512149,2.286594,338.406738,80.403526,83.577621,0.466298,83.577621,0.0
7104,393877.675575,186062.718750,-1.743964,3.041409,321.017822,76.243507,83.577621,0.379939,83.577621,0.0
7105,393877.678654,184887.500000,-1.953997,3.818105,299.879547,71.186501,83.577621,0.276626,83.577621,0.0
7106,393877.683402,185872.093750,-2.118591,4.488426,275.668365,65.394348,83.577621,0.170576,83.577621,0.0
7107,393877.690614,187246.171875,-2.216623,4.913417,249.288452,59.083363,83.577621,0.100718,83.577621,0.0
7108,393877.695780,186420.750000,-2.230155,4.973590,221.782669,52.503033,83.577621,0.107778,83.577621,0.0
7109,393877.700972,184977.218750,-2.144960,4.600855,194.238235,45.913452,83.577621,0.191620,83.577621,0.0
7110,393877.708505,185698.828125,-1.950957,3.806233,167.697708,39.564045,83.577621,0.267757,83.577621,0.0
7111,393877.715324,187171.093750,-1.642504,2.697820,143.080688,33.674805,28.421774,0.212294,28.421774,1.0
7112,393877.719159,186757.453125,-1.218569,1.484911,121.123009,28.421774,28.421774,-0.008875,28.421774,0.0
7113,393877.727951,185155.671875,-0.682729,0.466119,102.336426,23.927378,28.421774,-0.285398,28.421774,0.0
7114,393877.728914,185561.171875,-0.043016,0.001850,86.990707,20.256149,28.421774,-0.459613,28.421774,0.0
7115,393877.732983,187050.125000,0.688403,0.473899,75.117172,17.415594,28.421774,-0.452182,28.421774,0.0
7116,393877.736869,187067.125000,1.495689,2.237085,66.531601,15.361626,28.421774,-0.291085,28.421774,0.0
7117,393877.737963,185411.468750,2.359935,5.569292,60.872204,14.007704,28.421774,-0.063461,28.421774,0.0
7118,393877.750930,185444.500000,3.259892,10.626892,57.648083,13.236384,28.421774,0.141518,28.421774,0.0
7119,393877.756304,186872.453125,4.172760,17.411926,56.292706,12.912130,28.421774,0.262574,28.421774,0.0
7120,393877.760025,187320.750000,5.074989,25.755518,56.217175,12.894061,28.421774,0.269367,28.421774,0.0
7121,393877.766163,185728.046875,5.943044,35.319775,56.858604,13.047513,28.421774,0.165726,28.421774,0.0
7122,393877.769649,185348.468750,6.754121,45.618156,57.719971,13.253581,13.253581,-0.008427,13.253581,0.0
7123,393877.773449,186672.593750,7.486794,56.052082,58.398743,13.415967,13.253581,-0.190310,13.253581,0.0
7124,393877.779178,187515.578125,8.121570,65.959885,58.603283,13.464900,13.253581,-0.319216,13.253581,0.0
7125,393877.785868,186088.625000,8.641357,74.673058,58.157005,13.358136,13.253581,-0.368363,13.253581,0.0
7126,393877.794446,185302.203125,9.031880,81.574867,56.991680,13.079349,13.253581,-0.352940,13.253581,0.0
7127,393877.797559,186466.953125,9.281978,86.155113,55.132111,12.634476,13.253581,-0.300157,13.253581,0.0
7128,393877.811078,187624.625000,9.383850,88.056641,52.674946,12.046637,9.013670,-0.229541,9.013670,0.0
7129,393877.817935,186474.968750,9.333209,87.108788,49.764759,11.350421,9.013670,-0.159971,9.013670,0.0
7130,393877.824346,185309.046875,9.129309,83.344276,46.570118,10.586151,9.013670,-0.105658,9.013670,0.0
7131,393877.829861,186272.546875,8.774895,76.998779,43.262127,9.794766,9.013670,-0.072622,9.013670,0.0
7132,393877.831154,187660.703125,8.276027,68.492615,39.997143,9.013670,9.013670,-0.060583,9.013670,0.0
7133,393877.832188,186846.421875,7.641838,58.397694,36.904682,8.273847,9.013670,-0.051160,9.013670,0.0
7134,393877.837202,185410.296875,6.884232,47.392639,34.080921,7.598307,9.013670,-0.028155,9.013670,0.0
7135,393877.843919,186107.750000,6.017492,36.210205,31.587214,7.001726,5.069792,-0.008025,5.069792,0.0
7136,393877.848823,187598.078125,5.057889,25.582245,29.453030,6.491156,5.069792,-0.013540,5.069792,0.0
7137,393877.855896,187192.578125,4.023264,16.186657,27.681808,6.067419,5.069792,-0.039940,5.069792,0.0
7138,393877.857251,185594.218750,2.932587,8.600070,26.258545,5.726925,5.069792,-0.055776,5.069792,0.0
7139,393877.860956,185977.453125,1.805508,3.259860,25.157679,5.463560,5.069792,-0.034050,5.069792,0.0
7140,393877.865066,187471.000000,0.661893,0.438102,24.350143,5.270370,5.069792,-0.004502,5.069792,0.0
7141,393877.866152,187510.343750,-0.478631,0.229087,23.808804,5.140863,5.069792,-0.041887,5.069792,0.0
7142,393877.872907,185852.953125,-1.597094,2.550710,23.511730,5.069792,5.069792,-0.172291,5.069792,0.0
7143,393877.874813,185868.421875,-2.675557,7.158607,23.443371,5.053439,5.069792,-0.330469,5.069792,0.0
7144,393877.876123,187305.171875,-3.697423,13.670935,23.593760,5.089417,5.069792,-0.414441,5.069792,0.0
7145,393877.880773,187779.593750,-4.647710,21.601212,23.956305,5.176150,5.069792,-0.362231,5.069792,0.0
7146,393877.891823,186167.203125,-5.513286,30.396317,24.524807,5.312155,5.069792,-0.191762,5.069792,0.0
7147,393877.900544,185789.625000,-6.283031,39.476471,25.290339,5.495296,5.069792,0.024952,5.069792,0.0
7148,393877.905294,187112.093750,-6.947970,48.274292,26.238632,5.722160,5.069792,0.215812,5.069792,0.0
7149,393877.908779,187962.250000,-7.501350,56.270256,27.348434,5.987663,5.069792,0.336469,5.069792,0.0

In [154]:
mask_merged

0        False
1        False
2        False
3        False
4        False
         ...
22922    False
22923    False
22924    False
22925    False
22926    False
Name: offline z-score, Length: 22927, dtype: bool

In [159]:
offline_z_score = merged_df['offline z-score']
offline_z_score = np.array(offline_z_score)
offline_z_score[0]

nan