In [46]:
import numpy as np
import pandas as pd
import mne
import math

In [86]:
offline_full = pd.read_csv("eeg_LSL_gpype2back_nogui.csv")
offline_full

,Time,Ch01,Ch02,Ch03,Ch04,Ch05,Ch06,Ch07
0,401039.829417,199999.968750,-10266.498047,1.054010e+08,4.349291e+08,1.040500e+08,1.017940e+08,19.106939
1,401039.829566,199999.968750,-8758.502930,7.671138e+07,4.287422e+08,1.025699e+08,1.017940e+08,19.875378
2,401039.829784,199999.968750,-7280.627930,5.300754e+07,4.254989e+08,1.017940e+08,1.017940e+08,20.553970
3,401039.830036,199999.968750,-5851.947754,3.424529e+07,4.243946e+08,1.015298e+08,1.017940e+08,21.003149
4,401039.845197,199999.968750,-4487.628906,2.013881e+07,4.244573e+08,1.015448e+08,1.017940e+08,21.208216
...,...,...,...,...,...,...,...,...
25776,401142.962999,-10796.262695,-12.007365,1.441768e+02,3.837538e+03,9.175161e+02,9.452878e+02,-75.611000
25777,401142.967088,-10788.942383,-18.006073,3.242187e+02,3.768651e+03,9.010361e+02,9.452878e+02,-34.142731
25778,401142.978151,-10791.349609,-23.519312,5.531580e+02,3.682657e+03,8.804636e+02,9.452878e+02,3.758197
25779,401142.978421,-10478.307617,-28.499920,8.122454e+02,3.580433e+03,8.560078e+02,9.452878e+02,-4.691980
25780,401143.980460,0.000000,-32.911133,1.083143e+03,3.463768e+03,8.280975e+02,9.452878e+02,-51.952282

In [92]:
# channel_8 = df[['Time',' Ch08', ' Ch08_notched', ' Ch08_bp']]
channel_8 = offline_full.nlargest(10, "Ch07")
channel_8

,Time,Ch01,Ch02,Ch03,Ch04,Ch05,Ch06,Ch07
20062,401120.117527,-69033.539062,-50.092640,2509.272705,1067.095093,254.730881,254.730881,873.217773
23923,401135.559341,-22122.121094,11.340045,128.596634,148.629608,35.002300,34.389751,867.719910
21911,401127.508827,-36687.304688,10.876882,118.306557,153.244217,36.106274,35.239319,861.204956
23924,401135.559535,-22210.458984,13.259982,175.827118,152.132324,35.840271,34.389751,835.852844
21912,401127.509878,-36661.417969,12.682905,160.856079,156.383514,36.857300,36.857300,835.678223
20063,401120.117809,-68927.312500,-49.135956,2414.341797,1102.748413,263.260406,254.730881,833.920898
25681,401142.588281,-11975.432617,-44.159771,1950.085327,524.769714,124.987961,133.444824,768.424622
20061,401120.112009,-70188.539062,-50.187675,2518.802734,1027.762329,245.321136,181.664719,759.604370
25682,401142.588645,-11712.362305,-43.746765,1913.779297,560.119446,133.444824,133.444824,759.455383
23922,401135.559181,-21824.812500,9.175349,84.187035,146.069138,34.389751,34.389751,742.398438

In [187]:
pre = 2
post = 5
windows = []
for idx, event in enumerate(event_times): 
    mask = (raw['Time'] >= (event - pre)) & (raw['Time'] <= (event + post))
    window_df = raw.loc[mask].copy()
    window_df["t_rel"] = window_df["Time"] - event 
    window_df["idx"] = idx
    windows.append(window_df)

ValueError: picks ('Time') could not be interpreted as channel names (no channel "['Time']"), channel types (no type "Time" present), or a generic type (just "all" or "data")

In [ ]:
windows_df = pd.concat(windows, ignore_index=True)
windows_df_0 = windows_df[windows_df['idx']==0]
windows_df_0

In [ ]:
mask = merged_df[