In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
markers_df = pd.read_csv("lifu_markers_1_2back_sham.csv")
calibration_complete =markers_df[markers_df["marker"] == "START_EXPERIMENT_RECEIVED"].iloc[-1]
calibration_complete = calibration_complete["LSL_timestamp"]
markers_df_on = markers_df[markers_df["marker"] =="LIFU_ON"]
markers_df

           Time               marker  LSL_timestamp
0      2.837794  collecting_baseline  898814.006024
1      2.881106  collecting_baseline  898814.049337
2      2.915404  collecting_baseline  898814.083635
3      2.955411  collecting_baseline  898814.123641
4      3.001157  collecting_baseline  898814.169387
..          ...                  ...            ...
213  160.207192             LIFU_OFF  898971.375423
214  175.694626              LIFU_ON  898986.862856
215  180.698359             LIFU_OFF  898991.866589
216  191.404014              LIFU_ON  899002.572245
217  196.410979             LIFU_OFF  899007.579209

[218 rows x 3 columns]

In [3]:
calibration_complete  # remove w actual marker time

898867.6137661

In [4]:
eeg_df = pd.read_csv("scope_eeg_2back_sham.csv")
eeg_df

,Time,Ch01,Ch02,Ch03,Ch04,Ch05,Ch06,Ch07
0,898812.043533,-45606.855469,2315.561768,5.361826e+06,2.195369e+07,5.252079e+06,7.202526e+06,-7227.689941
1,898812.048925,-43945.386719,1977.758179,3.911528e+06,2.163855e+07,5.176686e+06,7.202526e+06,-7365.229492
2,898812.059241,-44758.542969,1646.568726,2.711189e+06,2.147280e+07,5.137034e+06,5.137034e+06,-7498.183594
3,898812.064916,-46566.585938,1326.272217,1.758998e+06,2.141590e+07,5.123420e+06,5.137034e+06,-7622.570312
4,898812.065773,-45930.199219,1020.274231,1.040960e+06,2.141879e+07,5.124114e+06,5.137034e+06,-7736.595215
...,...,...,...,...,...,...,...,...
48647,899009.013612,-59065.867188,0.346743,1.202305e-01,1.015791e+01,1.875097e+00,-2.780167e-01,-1.424296
48648,899009.019783,-59238.148438,0.222605,4.955307e-02,1.005938e+01,1.851526e+00,-2.780167e-01,-1.641190
48649,899009.021127,-59154.250000,0.125208,1.567695e-02,1.002963e+01,1.844409e+00,-2.780167e-01,-1.683182
48650,899009.023977,-58955.011719,0.054699,2.991986e-03,1.002867e+01,1.844179e+00,-2.780167e-01,-1.979088
48651,899009.029031,-59038.687500,0.010273,1.055248e-04,1.001744e+01,1.841494e+00,-2.780167e-01,-2.178208

In [5]:
eeg_df = eeg_df.rename(columns = {"Time": "LSL Time", "Ch01": "Raw", "Ch02": "Theta Bandpass", "Ch03": "Power", "Ch04": "Moving Average", "Ch05": "Z-score", "Ch06": "Hold", "Ch07": "Trigger Channel"})
eeg_df

,LSL Time,Raw,Theta Bandpass,Power,Moving Average,Z-score,Hold,Trigger Channel
0,898812.043533,-45606.855469,2315.561768,5.361826e+06,2.195369e+07,5.252079e+06,7.202526e+06,-7227.689941
1,898812.048925,-43945.386719,1977.758179,3.911528e+06,2.163855e+07,5.176686e+06,7.202526e+06,-7365.229492
2,898812.059241,-44758.542969,1646.568726,2.711189e+06,2.147280e+07,5.137034e+06,5.137034e+06,-7498.183594
3,898812.064916,-46566.585938,1326.272217,1.758998e+06,2.141590e+07,5.123420e+06,5.137034e+06,-7622.570312
4,898812.065773,-45930.199219,1020.274231,1.040960e+06,2.141879e+07,5.124114e+06,5.137034e+06,-7736.595215
...,...,...,...,...,...,...,...,...
48647,899009.013612,-59065.867188,0.346743,1.202305e-01,1.015791e+01,1.875097e+00,-2.780167e-01,-1.424296
48648,899009.019783,-59238.148438,0.222605,4.955307e-02,1.005938e+01,1.851526e+00,-2.780167e-01,-1.641190
48649,899009.021127,-59154.250000,0.125208,1.567695e-02,1.002963e+01,1.844409e+00,-2.780167e-01,-1.683182
48650,899009.023977,-58955.011719,0.054699,2.991986e-03,1.002867e+01,1.844179e+00,-2.780167e-01,-1.979088
48651,899009.029031,-59038.687500,0.010273,1.055248e-04,1.001744e+01,1.841494e+00,-2.780167e-01,-2.178208

In [6]:
lifu_on = markers_df[markers_df["marker"]=="LIFU_ON"].copy()
lifu_on_timestamp = lifu_on["LSL_timestamp"]
lifu_on_timestamp = np.array(lifu_on_timestamp)
lifu_on_timestamp

array([898868.2512194, 898883.9065124, 898898.9166517, 898914.2355922,
       898929.6814601, 898966.3711552, 898986.8628563, 899002.5722446])

In [7]:
target_ts = lifu_on_timestamp

tol = 3e-3  # tolerance for float comparison

df_matches = eeg_df[
    eeg_df["LSL Time"].apply(
        lambda x: np.any(np.abs(target_ts - x) < tol)
    )
]

df_matches

,LSL Time,Raw,Theta Bandpass,Power,Moving Average,Z-score,Hold,Trigger Channel
13981,898868.249360,38677.699219,-3.463216,11.993863,22.600399,4.851771,4.912069,-1.663493
13982,898868.250520,38702.394531,-3.577034,12.795169,22.852448,4.912069,4.912069,-1.754746
13983,898868.251810,39002.375000,-3.574672,12.778280,23.040720,4.957110,4.912069,-1.887126
17824,898883.903791,14625.335938,-3.645806,13.291901,8.904935,1.575343,1.527292,0.614743
17825,898883.905637,14701.343750,-3.726842,13.889356,8.975514,1.592229,1.527292,0.759063
21524,898898.913713,2330.660889,7.697799,59.256104,28.595001,6.285886,5.726718,-0.851390
21525,898898.917267,2109.933105,7.263835,52.763298,29.468191,6.494783,5.726718,-0.826904
25279,898914.233073,-5457.592285,4.784754,22.893871,12.290591,2.385309,2.562626,-1.658295
25280,898914.236716,-5460.191406,4.270434,18.236609,12.624741,2.465249,2.562626,-1.530071
29083,898929.679396,-11710.049805,-3.723869,13.867203,9.764336,1.780942,1.732495,-0.900198
29084,898929.683093,-11518.240234,-3.283757,10.783061,9.922114,1.818688,1.732495,-0.596610
38182,898966.368704,-36787.230469,-1.745175,3.045637,9.127075,1.628487,1.628487,0.672744
38183,898966.371451,-36992.957031,-1.501522,2.254568,9.135338,1.630464,1.628487,0.716393
38184,898966.372828,-36905.125000,-1.247847,1.557123,9.158173,1.635927,1.628487,0.630270
43227,898986.860445,-48993.042969,-7.215762,52.067223,15.006680,3.035091,1.589605,1.064641
43228,898986.862757,-48737.792969,-6.592103,43.455830,15.873860,3.242551,1.589605,1.018094
47075,899002.569629,-56533.699219,2.593352,6.725474,9.257576,1.659707,1.617497,-1.381488
47076,899002.572733,-56309.707031,3.513124,12.342039,9.495560,1.716641,1.617497,-1.114077
47077,899002.573638,-56261.710938,4.370168,19.098370,9.866735,1.805439,1.617497,-0.575764
47078,899002.574696,-56462.742188,5.144020,26.460943,10.382449,1.928816,1.617497,-0.273130

In [8]:
merged_df = eeg_df

In [9]:
buffer = []
offline_z = []
medians = []
mads = []
last_theta_val = None
last_median_val = None
last_mad_val = None

SONICATION_TIME = 5 #seconds i believe  
COOLDOWN_TIME = 15 #sonication time + cooldown time 
THETA_THRESHOLD_Z = 1.5    # z-score threshold
MU = 3.12
SIGMA =  5.31
MAD_THRESHOLD = 6       # for artifact rejection in baseline collection
INITIAL_CUTOFF = 100.0   # initial power threshold to exclude extreme artifacts
BUFFER_SIZE = 500
sonication_enabled = calibration_complete

# Ch05 = index 4
channel = "Hold"

for i in range(len(merged_df)):
    theta_val = merged_df[channel].iloc[i]   # MUST match online
    if last_theta_val is not None and theta_val == last_theta_val:
        offline_z.append(last_theta_val)
        medians.append(last_median_val)
        mads.append(last_theta_val)
        continue
    # Warm-up
    if len(buffer) <= 200:
        if theta_val < INITIAL_CUTOFF:
            buffer.append(theta_val)
        offline_z.append(np.nan)
        medians.append(np.nan)
        mads.append(np.nan)
        continue

    # Rolling buffer
    if len(buffer) > BUFFER_SIZE:
        buffer.pop(0)

    arr = np.array(buffer)
    median = np.median(arr)
    mad = np.median(np.abs(arr - median)) + 1e-6
    

    # Artifact rejection
    z_art = abs(theta_val - median) / mad
    if z_art > MAD_THRESHOLD:
        offline_z.append(np.nan)
        medians.append(np.nan)
        mads.append(np.nan)
        continue

    # Clean sample
    buffer.append(theta_val)
    last_theta_val = theta_val
    last_median_val = median
    last_mad_val = mad

    # Z-score
    offline_z.append(theta_val)
    medians.append(median)
    mads.append(mad)

merged_df["offline z-score"] = offline_z
merged_df["median"] = medians
merged_df['mad'] = mads

In [10]:
LIFU = np.zeros(len(merged_df))
last_trigger_time = -999

for i in range(len(merged_df)):
    theta_z = merged_df["offline z-score"].iloc[i]
    now = merged_df["LSL Time"].iloc[i]

    if now> sonication_enabled and theta_z > THETA_THRESHOLD_Z and theta_z < MAD_THRESHOLD and (now - last_trigger_time > COOLDOWN_TIME):
        LIFU[i] = 1.0
        last_trigger_time = now

In [11]:
merged_df["LIFU"] = LIFU
merged_df

,LSL Time,Raw,Theta Bandpass,Power,Moving Average,Z-score,Hold,Trigger Channel,offline z-score,median,mad,LIFU
0,898812.043533,-45606.855469,2315.561768,5.361826e+06,2.195369e+07,5.252079e+06,7.202526e+06,-7227.689941,NaN,NaN,NaN,0.0
1,898812.048925,-43945.386719,1977.758179,3.911528e+06,2.163855e+07,5.176686e+06,7.202526e+06,-7365.229492,NaN,NaN,NaN,0.0
2,898812.059241,-44758.542969,1646.568726,2.711189e+06,2.147280e+07,5.137034e+06,5.137034e+06,-7498.183594,NaN,NaN,NaN,0.0
3,898812.064916,-46566.585938,1326.272217,1.758998e+06,2.141590e+07,5.123420e+06,5.137034e+06,-7622.570312,NaN,NaN,NaN,0.0
4,898812.065773,-45930.199219,1020.274231,1.040960e+06,2.141879e+07,5.124114e+06,5.137034e+06,-7736.595215,NaN,NaN,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
48647,899009.013612,-59065.867188,0.346743,1.202305e-01,1.015791e+01,1.875097e+00,-2.780167e-01,-1.424296,-0.278017,0.216189,-0.278017,0.0
48648,899009.019783,-59238.148438,0.222605,4.955307e-02,1.005938e+01,1.851526e+00,-2.780167e-01,-1.641190,-0.278017,0.216189,-0.278017,0.0
48649,899009.021127,-59154.250000,0.125208,1.567695e-02,1.002963e+01,1.844409e+00,-2.780167e-01,-1.683182,-0.278017,0.216189,-0.278017,0.0
48650,899009.023977,-58955.011719,0.054699,2.991986e-03,1.002867e+01,1.844179e+00,-2.780167e-01,-1.979088,-0.278017,0.216189,-0.278017,0.0
48651,899009.029031,-59038.687500,0.010273,1.055248e-04,1.001744e+01,1.841494e+00,-2.780167e-01,-2.178208,-0.278017,0.216189,-0.278017,0.0

In [12]:
mask_lifu = merged_df["LIFU"] == 1.0
lifu_on_df = merged_df[mask_lifu]
lifu_on_df["LSL Time"] = lifu_on_df["LSL Time"]
lifu_on_cal = lifu_on_df[lifu_on_df["LSL Time"] > calibration_complete]
lifu_on_cal

C:\Users\jshin\AppData\Local\Temp\ipykernel_15932\4113107194.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lifu_on_df["LSL Time"] = lifu_on_df["LSL Time"]

,LSL Time,Raw,Theta Bandpass,Power,Moving Average,Z-score,Hold,Trigger Channel,offline z-score,median,mad,LIFU
13980,898868.246758,38951.949219,-3.234890,10.464513,22.381735,4.799459,4.912069,-1.575759,4.912069,2.243076,2.274371,1.0
17822,898883.893431,14433.646484,-3.292802,10.842545,8.704079,1.527292,1.527292,0.978341,1.527292,1.606154,1.573291,1.0
21519,898898.894675,2284.169434,7.121498,50.715740,22.646557,4.862813,4.832034,-1.553282,4.832034,0.827337,4.832034,1.0
25273,898914.226774,-5736.804688,6.065355,36.788532,8.643402,1.512776,2.562626,-0.606878,2.562626,0.800253,0.915416,1.0
28963,898929.227669,-11409.426758,1.204075,1.449796,16.947922,3.499503,1.880572,-0.213477,1.880572,0.570946,1.880572,1.0
38179,898966.361198,-36982.230469,-2.399009,5.755241,9.332296,1.677583,1.628487,0.466751,1.628487,-0.060883,0.300673,1.0
43221,898986.845098,-48775.394531,-7.381312,54.483776,7.765357,1.302717,1.589605,-0.075904,1.589605,-0.001400,0.352551,1.0
47072,899002.560600,-56268.582031,-0.320870,0.102957,9.081139,1.617497,1.617497,-0.072994,1.617497,0.055218,0.399530,1.0

In [13]:
lifu_on_time = lifu_on_cal["LSL Time"]
lifu_on_time = np.array(lifu_on_time)
offline_lifu= lifu_on_time

In [14]:
offline_lifu # because the begin calibration didn't start yet that's why it doesn't

array([898868.2467583, 898883.8934313, 898898.8946751, 898914.2267738,
       898929.2276686, 898966.3611976, 898986.8450976, 899002.5606005])

In [15]:
target_ts

array([898868.2512194, 898883.9065124, 898898.9166517, 898914.2355922,
       898929.6814601, 898966.3711552, 898986.8628563, 899002.5722446])

In [16]:
calibration_complete

898867.6137661

In [17]:
offline_lifu - target_ts

array([-0.0044611, -0.0130811, -0.0219766, -0.0088184, -0.4537915,
       -0.0099576, -0.0177587, -0.0116441])

In [41]:
channel_8 = eeg_df[eeg_df['LSL Time'] > calibration_complete]
channel_8 = channel_8.nlargest(25, "Trigger Channel")
channel_8

,LSL Time,Raw,Theta Bandpass,Power,Moving Average,Z-score,Hold,Trigger Channel,offline z-score,median,mad,LIFU
14045,898868.509449,38341.210938,-4.342668,18.858765,6.738875,1.057147,0.917419,894.199585,0.917419,2.264924,0.917419,0.0
17887,898884.153405,14433.004883,-4.528252,20.505062,8.804973,1.551429,1.015873,889.319641,1.015873,1.521123,1.015873,0.0
14046,898868.510132,38517.500000,-5.256754,27.633465,7.183495,1.163515,0.917419,849.823730,0.917419,2.264924,0.917419,0.0
17888,898884.155228,14338.302734,-4.031423,16.252375,9.116974,1.626070,1.015873,845.122742,1.015873,1.521123,1.015873,0.0
43306,898987.171534,-49229.511719,-3.885862,15.099922,30.597464,6.764944,6.734182,845.073914,NaN,NaN,NaN,0.0
43307,898987.175447,-48966.742188,-4.026042,16.209011,30.908438,6.839339,6.734182,827.039246,NaN,NaN,NaN,0.0
29133,898929.854028,-11732.841797,-2.269709,5.151580,5.296729,0.712136,0.753838,816.412964,0.753838,0.570946,0.753838,0.0
29134,898929.855846,-11577.083008,-2.302865,5.303188,5.187132,0.685917,0.753838,795.520996,0.753838,0.570946,0.753838,0.0
21577,898899.128047,2049.231689,-0.948257,0.899191,25.168407,5.466127,6.640703,780.578796,6.640703,0.890098,6.640703,0.0
25337,898914.447937,-5611.967773,2.436834,5.938159,19.396448,4.085275,3.818603,778.908508,3.818603,0.800253,3.818603,0.0
38245,898966.598973,-37063.531250,1.669295,2.786545,4.578827,0.540389,0.547351,773.573914,0.547351,-0.060883,0.547351,0.0
14044,898868.506713,38096.742188,-3.367563,11.340477,6.435245,0.984508,0.917419,767.665833,0.917419,2.264924,0.917419,0.0
17886,898884.146645,14189.958984,-4.917171,24.178568,8.421431,1.459673,1.015873,767.017456,1.015873,1.521123,1.015873,0.0
38246,898966.610716,-37162.855469,2.051828,4.209998,4.588428,0.542686,0.547351,756.867065,0.547351,-0.060883,0.547351,0.0
25338,898914.448301,-5521.035156,1.809002,3.272489,19.421112,4.091175,3.818603,755.808472,3.818603,0.800253,3.818603,0.0
21578,898899.128327,2185.010986,-1.696567,2.878338,24.724787,5.359997,6.640703,753.097839,6.640703,0.890098,6.640703,0.0
21576,898899.127346,1827.502563,-0.157306,0.024745,25.847092,5.628490,6.640703,746.597473,6.640703,0.890098,6.640703,0.0
25336,898914.443985,-5865.479004,3.030337,9.182943,19.286646,4.059006,3.818603,742.312683,3.818603,0.800253,3.818603,0.0
29132,898929.853677,-11669.565430,-2.218044,4.919717,5.471042,0.753838,0.753838,739.380554,0.753838,0.570946,0.753838,0.0
38244,898966.598527,-36853.769531,1.263342,1.596034,4.581438,0.541014,0.547351,732.619629,0.547351,-0.060883,0.547351,0.0
43305,898987.170668,-49137.261719,-3.624701,13.138455,30.303507,6.694620,6.734182,721.642273,NaN,NaN,NaN,0.0
43308,898987.179703,-48945.144531,-4.044673,16.359381,31.135708,6.893710,6.734182,718.582886,NaN,NaN,NaN,0.0
29135,898929.860521,-11434.460938,-2.315742,5.362663,5.138149,0.674198,0.753838,702.713562,0.753838,0.570946,0.753838,0.0
14047,898868.511182,38273.906250,-6.085147,37.029015,7.784180,1.307220,0.917419,701.755188,0.917419,2.264924,0.917419,0.0
17889,898884.156346,14076.424805,-3.433213,11.786955,9.348355,1.681425,1.015873,699.341187,1.015873,1.521123,1.015873,0.0

In [45]:
# channel_8 = eeg_df.nlargest(15, "Trigger Channel")
channel_8_sorted = channel_8.sort_values("LSL Time", ascending=False) # descending
MIN_SPACING = 10.0  # seconds
kept_rows = []
last_time = 0

for _, row in channel_8_sorted.iterrows():
    t = row["LSL Time"]
    if np.abs(t - last_time) >= MIN_SPACING:
        kept_rows.append(row)
        last_time = t
    if len(kept_rows) == 15:
        break
ttl_signal = pd.DataFrame(kept_rows)
ttl_signal_time = np.array(ttl_signal['LSL Time'])
ttl_signal_time = np.sort(ttl_signal_time)
target_ts[:-1]- ttl_signal_time

array([-0.2599625, -0.2498339, -0.2116757, -0.2127091, -0.1790605,
       -0.2395604, -0.3168465])

In [50]:
#windowing raw eeg
raw_with08 = pd.read_csv("offline_2back_sham.csv")
raw = raw_with08.drop(' Ch08', axis = 1)
pre = 2
post = 10
raw_windows = []
target_ts_onset = np.array(lifu_on['Time'])


for idx, event in enumerate(target_ts_onset): 
    mask = (raw['Time'] >= (event - pre)) & (raw['Time'] <= (event + post))
    window_df = raw.loc[mask].copy()
    window_df["t_rel"] = window_df["Time"] - event 
    window_df["idx"] = idx
    raw_windows.append(window_df)
raw_windows[0]

,Time,Ch01,Ch02,Ch03,Ch04,Ch05,Ch06,Ch07,t_rel,idx
13771,55.084,41802.718750,-452.947662,-7523.466309,122810.585938,-4342.842285,42655.019531,42106.917969,-1.998989,0
13772,55.088,41495.613281,-697.779663,-7696.366211,122791.539062,-4679.179688,42596.417969,42451.480469,-1.994989,0
13773,55.092,41454.625000,-1908.540771,-8372.307617,122955.476562,-6181.764648,42696.335938,43618.562500,-1.990989,0
13774,55.096,41774.417969,-1717.496094,-8243.156250,122945.148438,-5891.228027,42744.992188,43264.230469,-1.986989,0
13775,55.100,41795.667969,-618.672363,-7635.475098,122759.375000,-4524.518066,42627.480469,42161.042969,-1.982989,0
...,...,...,...,...,...,...,...,...,...,...
16766,67.064,19974.974609,-22164.656250,-29795.505859,86064.523438,-26245.333984,21069.933594,21270.302734,9.981011,0
16767,67.068,20044.759766,-23262.214844,-30397.656250,86230.062500,-27589.634766,21178.130859,22273.921875,9.985011,0
16768,67.072,20303.896484,-22741.916016,-30092.384766,86167.312500,-26896.646484,21172.431641,21586.755859,9.989011,0
16769,67.076,20240.500000,-21707.369141,-29518.890625,85997.921875,-25626.542969,21053.339844,20602.634766,9.993011,0
16770,67.080,19977.500000,-22007.349609,-29712.943359,86010.625000,-26040.318359,21036.197266,21055.916016,9.997011,0

In [51]:
#windowing scope eeg
pre = 2
post = 5
theta_windows = []


for idx, event in enumerate(target_ts): 
    mask = (eeg_df['LSL Time'] >= (event - pre)) & (eeg_df['LSL Time'] <= (event + post))
    window_df = eeg_df.loc[mask].copy()
    window_df["t_rel"] = window_df["LSL Time"] - event 
    window_df["idx"] = idx
    theta_windows.append(window_df)
theta_windows[0]

,LSL Time,Raw,Theta Bandpass,Power,Moving Average,Z-score,Hold,Trigger Channel,offline z-score,median,mad,LIFU,t_rel,idx
13478,898866.252276,43119.406250,-0.370534,0.137296,4.947315,0.628544,0.539197,1.061015,0.539197,2.293060,0.539197,0.0,-1.998944,0
13479,898866.265701,43396.187500,0.296053,0.087647,4.865458,0.608961,0.571616,1.129395,0.571616,2.287392,2.403110,0.0,-1.985518,0
13480,898866.267053,43262.960938,0.974134,0.948938,4.782367,0.589083,0.571616,0.953541,0.571616,2.287392,0.571616,0.0,-1.984166,0
13481,898866.268216,42960.386719,1.650162,2.723033,4.722298,0.574712,0.571616,0.615710,0.571616,2.287392,0.571616,0.0,-1.983003,0
13482,898866.271528,43014.835938,2.310456,5.338207,4.709353,0.571616,0.571616,0.285827,0.571616,2.287392,0.571616,0.0,-1.979692,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15227,898873.221429,28729.443359,-2.939843,8.642680,11.760366,2.258461,2.195040,-22.095236,2.195040,2.928111,2.195040,0.0,4.970210,0
15228,898873.231365,28749.277344,-2.649690,7.020858,11.768138,2.260320,2.195040,-36.157848,2.195040,2.928111,2.195040,0.0,4.980145,0
15229,898873.235572,29035.093750,-2.340272,5.476874,11.766731,2.259984,2.195040,1.269499,2.195040,2.928111,2.195040,0.0,4.984353,0
15230,898873.239227,29012.849609,-2.020113,4.080856,11.761304,2.258685,2.195040,37.607445,2.195040,2.928111,2.195040,0.0,4.988008,0
15231,898873.240437,28747.296875,-1.697468,2.881398,11.756599,2.257560,2.195040,21.967779,2.195040,2.928111,2.195040,0.0,4.989218,0

In [54]:
base_dir_raw = r"C:\Users\jshin\OW_closedloopLIFU\eeg_windows\raw"
base_dir_scope=r"C:\Users\jshin\OW_closedloopLIFU\eeg_windows\scope"
# MAKE SURE TO PUT IN NAME
new_folder_name = "sham1"
new_folder_path_raw = os.path.join(base_dir_raw, new_folder_name)
new_folder_path_scope = os.path.join(base_dir_scope, new_folder_name)
#os.makedirs(new_folder_path_raw, exist_ok=False) # check
os.makedirs(new_folder_path_scope, exist_ok=False) # check

for idx, event in enumerate(target_ts_onset):
    # Build a unique filename for each event
    #output_path_raw = os.path.join(new_folder_path_raw, f"{idx}_{event}_eeg_raw.csv")
    output_path_scope = os.path.join(new_folder_path_scope, f"{idx}_{event}_eeg_scope.csv")
    try:
        #raw_windows[idx].to_csv(output_path_raw, index=False, encoding="utf-8")
        theta_windows[idx].to_csv(output_path_scope, index=False, encoding="utf-8")
        #print(f"Saved successfully to: {output_path_raw}")
        print(f"Saved successfully to: {output_path_scope}")
    except (OSError, IOError) as e:
        print(f"Error saving CSV file: {e}")

Saved successfully to: C:\Users\jshin\OW_closedloopLIFU\eeg_windows\scope\sham1\0_57.08298870001454_eeg_scope.csv
Saved successfully to: C:\Users\jshin\OW_closedloopLIFU\eeg_windows\scope\sham1\1_72.73828170006163_eeg_scope.csv
Saved successfully to: C:\Users\jshin\OW_closedloopLIFU\eeg_windows\scope\sham1\2_87.74842100008391_eeg_scope.csv
Saved successfully to: C:\Users\jshin\OW_closedloopLIFU\eeg_windows\scope\sham1\3_103.0673614999978_eeg_scope.csv
Saved successfully to: C:\Users\jshin\OW_closedloopLIFU\eeg_windows\scope\sham1\4_118.51322940003593_eeg_scope.csv
Saved successfully to: C:\Users\jshin\OW_closedloopLIFU\eeg_windows\scope\sham1\5_155.2029244999867_eeg_scope.csv
Saved successfully to: C:\Users\jshin\OW_closedloopLIFU\eeg_windows\scope\sham1\6_175.6946256000083_eeg_scope.csv
Saved successfully to: C:\Users\jshin\OW_closedloopLIFU\eeg_windows\scope\sham1\7_191.40401390008628_eeg_scope.csv