In [1]:
import pyxdf
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [4]:
data, header = pyxdf.load_xdf("../lab_recorder_data/sub-scott_sham1_ses-scott_sham1_task-Default_run-001_eeg.xdf")
data

[{'info': defaultdict(list,
              {'name': ['PsychoPyMarkers'],
               'type': ['Markers'],
               'channel_count': ['1'],
               'channel_format': ['string'],
               'source_id': ['-4379379051682882619'],
               'nominal_srate': ['0.000000000000000'],
               'version': ['1.100000000000000'],
               'created_at': ['2126654.882835100'],
               'uid': ['443a876e-6c81-4320-b1c4-53fc740472e4'],
               'session_id': ['default'],
               'hostname': ['JanetsPC'],
               'v4address': [None],
               'v4data_port': ['16575'],
               'v4service_port': ['16580'],
               'v6address': [None],
               'v6data_port': ['16575'],
               'v6service_port': ['16580'],
               'desc': [None],
               'stream_id': 1,
               'effective_srate': 0,
               'segments': [(0, 99)],
               'clock_segments': [(0, 99)]}),
  'footer': {'info': defaultdict(list,
               {'first_timestamp': ['2126684.3765823'],
                'last_timestamp': ['2126882.3517803'],
                'sample_count': ['100'],
                'clock_offsets': [defaultdict(list,
                             {'offset': [defaultdict(list,
                                           {'time': ['2126677.56511925'],
                                            'value': ['-3.06498259305954e-05']}),
                               defaultdict(list,
                                           {'time': ['2126682.5654312'],
                                            'value': ['-1.619989052414894e-05']}),
                               defaultdict(list,
                                           {'time': ['2126687.56639515'],
                                            'value': ['-2.98498198390007e-05']}),
                               defaultdict(list,
                                           {'time': ['2126692.56662275'],
                                            'value': ['-2.60497909039259e-05']}),
                               defaultdict(list,
                                           {'time': ['2126697.5673378'],
                                            'value': ['-1.63000077009201e-05']}),
                               defaultdict(list,
                                           {'time': ['2126702.56801315'],
                                            'value': ['-2.144998870790005e-05']}),
                               defaultdict(list,
                                           {'time': ['2126707.5689371'],
                                            'value': ['-1.309975050389767e-05']}),
                               defaultdict(list,
                                           {'time': ['2126712.56912445'],
                                            'value': ['-1.835008151829243e-05']}),
                               defaultdict(list,
                                           {'time': ['2126717.56949935'],
                                            'value': ['-2.955016680061817e-05']}),
                               defaultdict(list,
                                           {'time': ['2126722.57024985'],
                                            'value': ['-2.205022610723972e-05']}),
                               defaultdict(list,
                                           {'time': ['2126727.57115355'],
                                            'value': ['-7.45011493563652e-06']}),
                               defaultdict(list,
                                           {'time': ['2126732.5719255'],
                                            'value': ['-1.41998752951622e-05']}),
                               defaultdict(list,
                                           {'time': ['2126737.57279845'],
                                            'value': ['-9.449897333979607e-06']}),
                               defaultdict(list,
                                           {'time': ['2126742.573707351'],
                                            'value': ['1.184991560876369e-05']}),
                               defaultdict(list,
                                           {'time': ['2126747.574574'],
                                            'value': ['-6.299931555986404e-06']}),
                               defaultdict(list,
                                           {'time': ['2126752.57509085'],
                                            'value': ['-6.249872967600822e-06']}),
                               defaultdict(list,
                                           {'time': ['2126757.57562085'],
                                            'value': ['-2.745003439486027e-05']}),
                               defaultdict(list,
                                           {'time': ['2126762.57608205'],
                                            'value': ['-4.45009209215641e-06']}),
                               defaultdict(list,
                                           {'time': ['2126767.57684405'],
                                            'value': ['-5.249865353107452e-06']}),
                               defaultdict(list,
                                           {'time': ['2126772.5778809'],
                                            'value': ['-1.299893483519554e-06']}),
                               defaultdict(list,
                                           {'time': ['2126777.5787891'],
                                            'value': ['-2.58998479694128e-05']}),
                               defaultdict(list,
                                           {'time': ['2126782.57945315'],
                                            'value': ['-1.244992017745972e-05']}),
                               defaultdict(list,
                                           {'time': ['2126787.58016285'],
                                            'value': ['-4.149973392486572e-06']}),
                               defaultdict(list,
                                           {'time': ['2126792.58122265'],
                                            'value': ['-8.449889719486237e-06']}),
                               defaultdict(list,
                                           {'time': ['2126797.58197745'],
                                            'value': ['-1.4500692486763e-06']}),
                               defaultdict(list,
                                           {'time': ['2126802.5830425'],
                                            'value': ['-1.229997724294662e-05']}),
                               defaultdict(list,
                                           {'time': ['2126807.5838662'],
                                            'value': ['-2.659996971487999e-05']}),
                               defaultdict(list,
                                           {'time': ['2126812.58456305'],
                                            'value': ['-1.275003887712955e-05']}),
                               defaultdict(list,
                                           {'time': ['2126817.5852632'],
                                            'value': ['-1.71000137925148e-05']}),
                               defaultdict(list,
                                           {'time': ['2126822.5854375'],
                                            'value': ['-1.569977030158043e-05']}),
                               defaultdict(list,
                                           {'time': ['2126827.58630435'],
                                            'value': ['-2.505001612007618e-05']}),
                               defaultdict(list,
                                           {'time': ['2126832.5871978'],
                                            'value': ['-1.029996201395988e-05']}),
                               defaultdict(list,
                                           {'time': ['2126837.587648951'],
                                            'value': ['-1.515005715191364e-05']}),
                               defaultdict(list,
                                           {'time': ['2126842.58867675'],
                                            'value': ['-1.465016975998878e-05']}),
                               defaultdict(list,
                                           {'time': ['2126847.58877125'],
                                            'value': ['3.150198608636856e-06']}),
                               defaultdict(list,
                                           {'time': ['2126852.5892165'],
                                            'value': ['-1.170020550489426e-05']}),
                               defaultdict(list,
                                           {'time': ['2126857.5895119'],
                                            'value': ['-2.130004577338696e-05']}),
                               defaultdict(list,
                                           {'time': ['2126862.5898326'],
                                            'value': ['-1.33998692035675e-05']}),
                               defaultdict(list,
                                           {'time': ['2126867.59029285'],
                                            'value': ['-9.550014510750771e-06']}),
                               defaultdict(list,
                                           {'time': ['2126872.5903658'],
                                            'value': ['7.399823516607285e-06']}),
                               defaultdict(list,
                                           {'time': ['2126877.59107125'],
                                            'value': ['-1.455028541386127e-05']}),
                               defaultdict(list,
                                           {'time': ['2126882.591927'],
                                            'value': ['-1.140008680522442e-05']}),
                               defaultdict(list,
                                           {'time': ['2126887.59276195'],
                                            'value': ['-1.864996738731861e-05']}),
                               defaultdict(list,
                                           {'time': ['2126892.5928566'],
                                            'value': ['-1.659989356994629e-05']}),
                               defaultdict(list,
                                           {'time': ['2126897.5937543'],
                                            'value': ['-1.659989356994629e-05']}),
                               defaultdict(list,
                                           {'time': ['2126902.5947527'],
                                            'value': ['-1.659989356994629e-05']}),
                               defaultdict(list,
                                           {'time': ['2126907.5950348'],
                                            'value': ['-1.659989356994629e-05']}),
                               defaultdict(list,
                                           {'time': ['2126912.5959764'],
                                            'value': ['-1.659989356994629e-05']})]})]})},
  'time_series': [['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT'],
   ['START_EXPERIMENT']],
  'time_stamps': array([2126684.37656568, 2126686.37574733, 2126688.36949607,
         2126690.36243202, 2126692.35638887, 2126694.35944742,
         2126696.35104387, 2126698.35242092, 2126700.35388707,
         2126702.35584351, 2126704.35750166, 2126706.35901651,
         2126708.35241166, 2126710.35439031, 2126712.35570176,
         2126714.35719241, 2126716.35935455, 2126718.3522035 ,
         2126720.35375485, 2126722.3550915 , 2126724.35697565,
         2126726.3585333 , 2126728.35238645, 2126730.35363989,
         2126732.35525394, 2126734.35698529, 2126736.35806654,
         2126738.35121699, 2126740.35329364, 2126742.35407229,
         2126744.35593573, 2126746.35768338, 2126748.35955503,
         2126750.35260038, 2126752.35526943, 2126754.35659778,
         2126756.35768613, 2126758.35160607, 2126760.35242212,
         2126762.35417627, 2126764.35677392, 2126766.35783297,
         2126768.35942272, 2126770.35206047, 2126772.35362431,
         2126774.35566236, 2126776.35754121, 2126778.35857686,
         2126780.35290381, 2126782.35350996, 2126784.35584261,
         2126786.35710955, 2126788.3586298 , 2126790.35187245,
         2126792.353835  , 2126794.35548105, 2126796.3574115 ,
         2126798.35892085, 2126800.35136399, 2126802.35371734,
         2126804.35473479, 2126806.35646964, 2126808.35803719,
         2126810.35170954, 2126812.35335769, 2126814.35490343,
         2126816.36159388, 2126818.35849103, 2126820.35100688,
         2126822.35288183, 2126824.35442808, 2126826.35589423,
         2126828.35761197, 2126830.35923572, 2126832.36229387,
         2126834.35389542, 2126836.35485237, 2126838.35736412,
         2126840.35913027, 2126842.35210441, 2126844.35420436,
         2126846.35568741, 2126848.35694716, 2126850.35882571,
         2126852.35178146, 2126854.35324871, 2126856.35549816,
         2126858.3569294 , 2126860.35875005, 2126862.352213  ,
         2126864.35385285, 2126866.3555133 , 2126868.35693565,
         2126870.3581122 , 2126872.35119974, 2126874.35338769,
         2126876.35450764, 2126878.35600959, 2126880.35849924,
         2126882.35176849]),
  'clock_times': [2126677.5651192497,
   2126682.5654312,
   2126687.56639515,
   2126692.56662275,
   2126697.5673378,
   2126702.5680131502,
   2126707.5689370995,
   2126712.56912445,
   2126717.56949935,
   2126722.57024985,
   2126727.57115355,
   2126732.5719255,
   2126737.5727984495,
   2126742.5737073505,
   2126747.5745739997,
   2126752.57509085,
   2126757.5756208496,
   2126762.57608205,
   2126767.57684405,
   2126772.5778809004,
   2126777.5787891,
   2126782.57945315,
   2126787.5801628497,
   2126792.5812226497,
   2126797.5819774503,
   2126802.5830425,
   2126807.5838662,
   2126812.5845630504,
   2126817.5852632,
   2126822.5854375,
   2126827.58630435,
   2126832.5871978,
   2126837.5876489505,
   2126842.58867675,
   2126847.5887712496,
   2126852.5892165,
   2126857.5895119,
   2126862.5898325997,
   2126867.5902928496,
   2126872.5903658,
   2126877.59107125,
   2126882.5919270003,
   2126887.5927619496,
   2126892.5928566,
   2126897.5937543,
   2126902.5947527,
   2126907.5950348,
   2126912.5959763997],
  'clock_values': [-3.06498259305954e-05,
   -1.619989052414894e-05,
   -2.9849819839000702e-05,
   -2.6049790903925896e-05,
   -1.6300007700920105e-05,
   -2.1449988707900047e-05,
   -1.3099750503897667e-05,
   -1.8350081518292427e-05,
   -2.955016680061817e-05,
   -2.2050226107239723e-05,
   -7.45011493563652e-06,
   -1.4199875295162201e-05,
   -9.449897333979607e-06,
   1.1849915608763695e-05,
   -6.299931555986404e-06,
   -6.2498729676008224e-06,
   -2.7450034394860268e-05,
   -4.45009209215641e-06,
   -5.249865353107452e-06,
   -1.2998934835195541e-06,
   -2.5899847969412804e-05,
   -1.2449920177459717e-05,
   -4.149973392486572e-06,
   -8.449889719486237e-06,
   -1.4500692486763e-06,
   -1.2299977242946625e-05,
   -2.659996971487999e-05,
   -1.2750038877129555e-05,
   -1.71000137925148e-05,
   -1.569977030158043e-05,
   -2.505001612007618e-05,
   -1.0299962013959885e-05,
   -1.5150057151913643e-05,
   -1.4650169759988785e-05,
   3.150198608636856e-06,
   -1.1700205504894257e-05,
   -2.1300045773386955e-05,
   -1.3399869203567505e-05,
   -9.55001451075077e-06,
   7.3998235166072845e-06,
   -1.4550285413861275e-05,
   -1.1400086805224419e-05,
   -1.864996738731861e-05,
   -1.659989356994629e-05,
   -1.659989356994629e-05,
   -1.659989356994629e-05,
   -1.659989356994629e-05,
   -1.659989356994629e-05]},
 {'info': defaultdict(list,
              {'name': ['EEG_LIFU_events'],
               'type': ['Markers'],
               'channel_count': ['1'],
               'channel_format': ['string'],
               'source_id': [None],
               'nominal_srate': ['0.000000000000000'],
               'version': ['1.100000000000000'],
               'created_at': ['2126558.199484500'],
               'uid': ['d4dee8e1-eee7-4a1e-951e-b95fc7c653c3'],
               'session_id': ['default'],
               'hostname': ['JanetsPC'],
               'v4address': [None],
               'v4data_port': ['16572'],
               'v4service_port': ['16572'],
               'v6address': [None],
               'v6data_port': ['16572'],
               'v6service_port': ['16572'],
               'desc': [None],
               'stream_id': 3,
               'effective_srate': 0,
               'segments': [(0, 22)],
               'clock_segments': [(0, 22)]}),
  'time_series': [['START_EXPERIMENT_RECEIVED'],
   ['LIFU_ON'],
   ['LIFU_OFF'],
   ['LIFU_ON'],
   ['LIFU_OFF'],
   ['LIFU_ON'],
   ['LIFU_OFF'],
   ['LIFU_ON'],
   ['LIFU_OFF'],
   ['LIFU_ON'],
   ['LIFU_OFF'],
   ['LIFU_ON'],
   ['LIFU_OFF'],
   ['LIFU_ON'],
   ['LIFU_OFF'],
   ['LIFU_ON'],
   ['LIFU_OFF'],
   ['LIFU_ON'],
   ['LIFU_OFF'],
   ['LIFU_ON'],
   ['LIFU_OFF'],
   ['LIFU_ON'],
   ['LIFU_OFF']],
  'time_stamps': array([2126684.37752257, 2126684.8026258 , 2126689.80346598,
         2126701.73062089, 2126706.73183387, 2126721.61227271,
         2126726.61298129, 2126736.73185857, 2126741.73339405,
         2126752.12881684, 2126757.12958772, 2126768.73627831,
         2126773.73706869, 2126786.04525023, 2126791.04631982,
         2126802.6570825 , 2126807.65884069, 2126817.73118836,
         2126822.73142794, 2126833.77098548, 2126838.77130086,
         2126850.41133355, 2126855.41224283]),

In [ ]:
data

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,42082.648438,20786.525391,10384.942383,13134.862305,32778.500000,50584.773438,56421.093750,0.533888,0.285036,1.941486,-0.517957,-0.374694,-0.415687
1,41866.519531,20716.193359,10511.184570,13218.117188,32831.218750,50300.460938,56478.835938,0.247424,0.061219,1.795327,-0.540102,-0.374694,-0.546212
2,42414.187500,21033.291016,10112.310547,12833.953125,32569.150391,50980.550781,56422.710938,-0.057246,0.003277,1.662127,-0.560284,-0.560284,-0.594477
3,42800.429688,21225.953125,9883.427734,12634.445312,32442.240234,51498.230469,56354.480469,-0.372842,0.139011,1.548129,-0.577556,-0.560284,-0.494768
4,42137.511719,20810.130859,10316.659180,13035.036133,32732.417969,50667.148438,56380.113281,-0.691347,0.477961,1.458847,-0.591084,-0.560284,-0.295945
...,...,...,...,...,...,...,...,...,...,...,...,...,...
57541,41172.554688,20478.896484,9971.596680,13088.465820,32628.464844,39031.148438,56847.699219,-21.081528,444.430817,114.382103,16.518503,10.832265,-0.062478
57542,41571.050781,20707.964844,9636.474609,12801.934570,32424.740234,39632.136719,56720.281250,-21.398880,457.912048,123.532997,17.904999,17.904999,-0.095029
57543,40984.707031,20331.552734,10063.195312,13272.833984,32685.687500,38858.843750,56758.242188,-21.262808,452.107025,132.488159,19.261841,17.904999,-0.130580
57544,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-20.673401,427.389496,140.783890,20.518774,17.904999,-1.747336
57545,40988.113281,20610.333984,10028.648438,13163.757812,32641.437500,39100.742188,56791.406250,-1.912486,3.657602,16.872086,1.744256,1.772836,0.105052

In [16]:
stream = data[3]
df= []
df = pd.DataFrame(stream['time_series'])
df = df.rename(columns={i: f"Ch{i}" for i in range(df.shape[1])})

# Add timestamp column
df['Timestamp'] = stream['time_stamps']

# Move Timestamp to be the first column after the index
cols = ['Timestamp'] + [col for col in df.columns if col != 'Timestamp']
df = df[cols]
df

,Timestamp,Ch0,Ch1,Ch2,Ch3,Ch4,Ch5,Ch6,Ch7,Ch8,Ch9,Ch10,Ch11,Ch12
0,2.126672e+06,42082.648438,20786.525391,10384.942383,13134.862305,32778.500000,50584.773438,56421.093750,0.533888,0.285036,1.941486,-0.517957,-0.374694,-0.415687
1,2.126672e+06,41866.519531,20716.193359,10511.184570,13218.117188,32831.218750,50300.460938,56478.835938,0.247424,0.061219,1.795327,-0.540102,-0.374694,-0.546212
2,2.126672e+06,42414.187500,21033.291016,10112.310547,12833.953125,32569.150391,50980.550781,56422.710938,-0.057246,0.003277,1.662127,-0.560284,-0.560284,-0.594477
3,2.126672e+06,42800.429688,21225.953125,9883.427734,12634.445312,32442.240234,51498.230469,56354.480469,-0.372842,0.139011,1.548129,-0.577556,-0.560284,-0.494768
4,2.126672e+06,42137.511719,20810.130859,10316.659180,13035.036133,32732.417969,50667.148438,56380.113281,-0.691347,0.477961,1.458847,-0.591084,-0.560284,-0.295945
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57541,2.126902e+06,41172.554688,20478.896484,9971.596680,13088.465820,32628.464844,39031.148438,56847.699219,-21.081528,444.430817,114.382103,16.518503,10.832265,-0.062478
57542,2.126902e+06,41571.050781,20707.964844,9636.474609,12801.934570,32424.740234,39632.136719,56720.281250,-21.398880,457.912048,123.532997,17.904999,17.904999,-0.095029
57543,2.126902e+06,40984.707031,20331.552734,10063.195312,13272.833984,32685.687500,38858.843750,56758.242188,-21.262808,452.107025,132.488159,19.261841,17.904999,-0.130580
57544,2.126902e+06,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-20.673401,427.389496,140.783890,20.518774,17.904999,-1.747336
57545,2.126902e+06,40988.113281,20610.333984,10028.648438,13163.757812,32641.437500,39100.742188,56791.406250,-1.912486,3.657602,16.872086,1.744256,1.772836,0.105052

In [23]:
print("Streams found:", [s['info']['name'][0] for s in data])

Streams found: ['PsychoPyMarkers', 'EEG_LIFU_events', 'PsychoPy_numeric', 'EEG_gpype']

In [41]:
EEG_LIFU_events = data[1]

# Create DataFrame from time_series
markers = pd.DataFrame(EEG_LIFU_events['time_series'])

# Rename the first column to 'markers'
markers.rename(columns={0: 'markers'}, inplace=True)

# Add timestamp column
markers['Timestamp'] = EEG_LIFU_events['time_stamps']

# Move Timestamp to be the first column after the index
cols = ['Timestamp'] + [col for col in markers.columns if col != 'Timestamp']
markers = markers[cols]
markers

       Timestamp                    markers
0   2.126684e+06  START_EXPERIMENT_RECEIVED
1   2.126685e+06                    LIFU_ON
2   2.126690e+06                   LIFU_OFF
3   2.126702e+06                    LIFU_ON
4   2.126707e+06                   LIFU_OFF
5   2.126722e+06                    LIFU_ON
6   2.126727e+06                   LIFU_OFF
7   2.126737e+06                    LIFU_ON
8   2.126742e+06                   LIFU_OFF
9   2.126752e+06                    LIFU_ON
10  2.126757e+06                   LIFU_OFF
11  2.126769e+06                    LIFU_ON
12  2.126774e+06                   LIFU_OFF
13  2.126786e+06                    LIFU_ON
14  2.126791e+06                   LIFU_OFF
15  2.126803e+06                    LIFU_ON
16  2.126808e+06                   LIFU_OFF
17  2.126818e+06                    LIFU_ON
18  2.126823e+06                   LIFU_OFF
19  2.126834e+06                    LIFU_ON
20  2.126839e+06                   LIFU_OFF
21  2.126850e+06                    LIFU_ON
22  2.126855e+06                   LIFU_OFF

In [37]:
lifu_on = markers[markers['markers'] == 'LIFU_ON']
lifu_on = np.array(lifu_on['Timestamp'])
lifu_on

array([2126684.8026258 , 2126701.73062089, 2126721.61227271,
       2126736.73185857, 2126752.12881684, 2126768.73627831,
       2126786.04525023, 2126802.6570825 , 2126817.73118836,
       2126833.77098548, 2126850.41133355])

In [53]:
start = markers[markers['markers'] == 'START_EXPERIMENT_RECEIVED']
start = start.iloc[0]['Timestamp']

In [61]:
buffer = []
offline_z = []
medians = []
merged_df = df
mads = []
last_theta_val = None
last_median_val = None
last_mad_val = None

SONICATION_TIME = 5 #seconds i believe  
COOLDOWN_TIME = 15 #sonication time + cooldown time 
THETA_THRESHOLD_Z = 1.5    # z-score threshold
MU =  5.36
SIGMA =  6.60
MAD_THRESHOLD = 6       # for artifact rejection in baseline collection
INITIAL_CUTOFF = 50.0   # initial power threshold to exclude extreme artifacts
BUFFER_SIZE = 500
sonication_enabled = start

# Ch05 = index 4
channel = "Ch11"

for i in range(len(merged_df)):
    theta_val = merged_df[channel].iloc[i]   # MUST match online
    if last_theta_val is not None and theta_val == last_theta_val:
        offline_z.append(last_theta_val)
        medians.append(last_median_val)
        mads.append(last_theta_val)
        continue
    # Warm-up
    if len(buffer) <= 200:
        if theta_val < INITIAL_CUTOFF:
            buffer.append(theta_val)
        offline_z.append(np.nan)
        medians.append(np.nan)
        mads.append(np.nan)
        continue

    # Rolling buffer
    if len(buffer) > BUFFER_SIZE:
        buffer.pop(0)

    arr = np.array(buffer)
    median = np.median(arr)
    mad = np.median(np.abs(arr - median)) + 1e-6
    

    # Artifact rejection
    z_art = abs(theta_val - median) / mad
    if z_art > MAD_THRESHOLD:
        offline_z.append(np.nan)
        medians.append(np.nan)
        mads.append(np.nan)
        continue

    # Clean sample
    buffer.append(theta_val)
    last_theta_val = theta_val
    last_median_val = median
    last_mad_val = mad

    # Z-score
    offline_z.append(theta_val)
    medians.append(median)
    mads.append(mad)

merged_df["offline z-score"] = offline_z
merged_df["median"] = medians
merged_df['mad'] = mads

In [62]:
LIFU = np.zeros(len(merged_df))
last_trigger_time = -999

for i in range(len(merged_df)):
    theta_z = merged_df["offline z-score"].iloc[i]
    now = merged_df["Timestamp"].iloc[i]

    if now> sonication_enabled and theta_z > THETA_THRESHOLD_Z and theta_z < MAD_THRESHOLD and (now - last_trigger_time > COOLDOWN_TIME):
        LIFU[i] = 1.0
        last_trigger_time = now

In [63]:
merged_df["LIFU"] = LIFU
merged_df

,Timestamp,Ch0,Ch1,Ch2,Ch3,Ch4,Ch5,Ch6,Ch7,Ch8,Ch9,Ch10,Ch11,Ch12,offline z-score,median,mad,LIFU
0,2.126672e+06,42082.648438,20786.525391,10384.942383,13134.862305,32778.500000,50584.773438,56421.093750,0.533888,0.285036,1.941486,-0.517957,-0.374694,-0.415687,NaN,NaN,NaN,0.0
1,2.126672e+06,41866.519531,20716.193359,10511.184570,13218.117188,32831.218750,50300.460938,56478.835938,0.247424,0.061219,1.795327,-0.540102,-0.374694,-0.546212,NaN,NaN,NaN,0.0
2,2.126672e+06,42414.187500,21033.291016,10112.310547,12833.953125,32569.150391,50980.550781,56422.710938,-0.057246,0.003277,1.662127,-0.560284,-0.560284,-0.594477,NaN,NaN,NaN,0.0
3,2.126672e+06,42800.429688,21225.953125,9883.427734,12634.445312,32442.240234,51498.230469,56354.480469,-0.372842,0.139011,1.548129,-0.577556,-0.560284,-0.494768,NaN,NaN,NaN,0.0
4,2.126672e+06,42137.511719,20810.130859,10316.659180,13035.036133,32732.417969,50667.148438,56380.113281,-0.691347,0.477961,1.458847,-0.591084,-0.560284,-0.295945,NaN,NaN,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57541,2.126902e+06,41172.554688,20478.896484,9971.596680,13088.465820,32628.464844,39031.148438,56847.699219,-21.081528,444.430817,114.382103,16.518503,10.832265,-0.062478,NaN,NaN,NaN,0.0
57542,2.126902e+06,41571.050781,20707.964844,9636.474609,12801.934570,32424.740234,39632.136719,56720.281250,-21.398880,457.912048,123.532997,17.904999,17.904999,-0.095029,NaN,NaN,NaN,0.0
57543,2.126902e+06,40984.707031,20331.552734,10063.195312,13272.833984,32685.687500,38858.843750,56758.242188,-21.262808,452.107025,132.488159,19.261841,17.904999,-0.130580,NaN,NaN,NaN,0.0
57544,2.126902e+06,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-20.673401,427.389496,140.783890,20.518774,17.904999,-1.747336,NaN,NaN,NaN,0.0
57545,2.126902e+06,40988.113281,20610.333984,10028.648438,13163.757812,32641.437500,39100.742188,56791.406250,-1.912486,3.657602,16.872086,1.744256,1.772836,0.105052,NaN,NaN,NaN,0.0

In [64]:
mask_lifu = merged_df["LIFU"] == 1.0
lifu_on_df = merged_df[mask_lifu]
lifu_on_df["Timestamp"] = lifu_on_df["Timestamp"]
lifu_on_cal = lifu_on_df[lifu_on_df["Timestamp"] > start]
lifu_on_cal

C:\Users\jshin\AppData\Local\Temp\ipykernel_6808\1311862906.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lifu_on_df["Timestamp"] = lifu_on_df["Timestamp"]

,Timestamp,Ch0,Ch1,Ch2,Ch3,Ch4,Ch5,Ch6,Ch7,Ch8,Ch9,Ch10,Ch11,Ch12,offline z-score,median,mad,LIFU
3222,2.126685e+06,41547.875000,20569.015625,10615.921875,10512.208984,32972.023438,50409.031250,56659.417969,-8.046468,64.745644,21.560394,2.454605,2.454605,0.120880,2.454605,-0.075113,0.484928,1.0
7452,2.126702e+06,41266.250000,20729.853516,10340.976562,8540.036133,32853.800781,50552.273438,56686.187500,4.051147,16.411789,17.236609,1.799486,1.799486,-0.281466,1.799486,-0.066250,0.402780,1.0
12422,2.126722e+06,40933.750000,20852.042969,10112.096680,8336.091797,32720.927734,50739.488281,56553.750000,-7.414465,54.974297,15.560725,1.545565,1.545565,-0.149320,1.545565,-0.196175,0.330812,1.0
16201,2.126737e+06,41324.238281,21406.984375,9601.640625,8603.073242,32355.621094,51570.824219,56470.085938,-7.637331,58.328827,16.793329,1.732323,1.924567,-0.126421,1.924567,-0.196385,0.371643,1.0
20052,2.126752e+06,41107.468750,21378.662109,9659.458008,6987.048340,32327.964844,51580.957031,56500.960938,3.429293,11.760054,16.931911,1.753320,1.753320,0.314565,1.753320,0.089161,0.448737,1.0
24202,2.126769e+06,41061.574219,21523.000000,9786.416992,4930.115723,32397.083984,51654.917969,56641.800781,8.081001,65.302589,21.252802,2.408000,2.408000,-0.378362,2.408000,-0.063966,0.489539,1.0
28532,2.126786e+06,40780.480469,21243.121094,9706.044922,4262.662598,32340.603516,51487.398438,56476.593750,0.922336,0.850705,15.841594,1.588120,1.588120,0.001822,1.588120,-0.177133,0.393123,1.0
32682,2.126803e+06,40831.144531,21407.990234,9592.200195,7854.628906,32230.740234,51574.949219,56472.355469,-4.561038,20.803066,17.437481,1.829921,1.829921,-0.258510,1.829921,0.056214,0.467671,1.0
36452,2.126818e+06,40407.761719,21028.568359,10124.349609,8011.460938,32648.947266,43536.886719,56695.937500,-5.631065,31.708899,26.841900,3.254833,3.254833,-0.007448,3.254833,0.148954,0.617534,1.0
40462,2.126834e+06,40700.988281,21211.531250,9937.906250,9149.528320,32540.656250,40049.625000,56547.675781,6.450368,41.607258,15.545135,1.543202,1.543202,-0.365366,1.543202,0.453352,0.842431,1.0
44622,2.126850e+06,40560.082031,20993.806641,10325.362305,12613.250000,32908.437500,39255.144531,56847.582031,6.217666,38.659363,17.701874,1.869981,1.869981,0.593492,1.869981,0.272246,0.699495,1.0
48682,2.126867e+06,41197.113281,21089.171875,9796.596680,12393.404297,32662.396484,39686.707031,56707.386719,0.701164,0.491630,16.120941,1.630446,1.630446,-0.173648,1.630446,-0.229872,0.341276,1.0

In [67]:
offline = np.array(lifu_on_cal['Timestamp'])
offline

array([2126684.80441875, 2126701.72515681, 2126721.60602398,
       2126736.72268335, 2126752.12735528, 2126768.72807938,
       2126786.04883488, 2126802.64955898, 2126817.73021677,
       2126833.77091644, 2126850.41164229, 2126866.65235068])

In [68]:
online = lifu_on
online

array([2126684.8026258 , 2126701.73062089, 2126721.61227271,
       2126736.73185857, 2126752.12881684, 2126768.73627831,
       2126786.04525023, 2126802.6570825 , 2126817.73118836,
       2126833.77098548, 2126850.41133355])

In [70]:
online - offline[:-1]

array([-1.79295568e-03,  5.46408119e-03,  6.24872744e-03,  9.17521678e-03,
        1.46156549e-03,  8.19893600e-03, -3.58464615e-03,  7.52352457e-03,
        9.71581321e-04,  6.90361485e-05, -3.08735296e-04])